name: Scheduled Issue updates
description:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - description: "Close issues that where author has not provided reproduction code or repo"
      - frequencies:
          - hourly:
              hour: 3
        filters:
          - isOpen
          - is:issue
          - hasLabel:
              label: Needs repro code or repository
          - noActivitySince:
              days: 1
        actions:
          - addReply:
              reply: "This issue has been automatically closed as no reproduction code has been provided within **4 days**."
          - closeIssue
