name: Scheduled Issue updates
description: "Scheduled task to close stale issues"
resource: repository
disabled: false
where:
  resource: repository
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - description: "Close issues where author has not provided reproduction code or repo"
        frequencies:
          - hourly:
              hour: 3
        filters:
          - isOpen: true
          - is: issue
          - hasLabel:
              label: Needs repro code or repository
          - noActivitySince:
              days: 1
        actions:
          - addReply:
              reply: "This issue has been automatically closed as no reproduction code has been provided within **4 days**."
          - closeIssue: true
