name: Issue Triage
description: Assign label to new issues without a label
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Add labels to unassigned issue
        triggerOnOwnActions: false
        if:
          - payloadType: Issues
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
          - addLabel:
              label: triage
