// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable 1591

namespace Microsoft.FluentUI.AspNetCore.Components.Icons.Light;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static partial class Size28
{
    public class Document : Icon { public Document() : base("Document", IconVariant.Light, IconSize.Size28, "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"28\" height=\"28\" viewBox=\"0 0 28 28\"><path d=\"M5 4.5C5 3.67 5.67 3 6.5 3H14v6.5a2.5 2.5 0 0 0 2.5 2.5H23v11.5c0 .83-.67 1.5-1.5 1.5h-15A1.5 1.5 0 0 1 5 23.5zM22.96 11H16.5A1.5 1.5 0 0 1 15 9.5V3.04q.42.1.73.4l6.83 6.83q.3.3.4.73M6.5 2A2.5 2.5 0 0 0 4 4.5v19A2.5 2.5 0 0 0 6.5 26h15a2.5 2.5 0 0 0 2.5-2.5V11.33c0-.66-.26-1.3-.73-1.77l-6.83-6.83A2.5 2.5 0 0 0 14.67 2z\"/>") { } }
    public class DocumentSparkle : Icon { public DocumentSparkle() : base("DocumentSparkle", IconVariant.Light, IconSize.Size28, "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"28\" height=\"28\" viewBox=\"0 0 28 28\"><path d=\"M6.5 3C5.67 3 5 3.67 5 4.5v8.49h-.05q-.52 0-.95.3V4.5A2.5 2.5 0 0 1 6.5 2h8.17c.66 0 1.3.26 1.77.73l6.83 6.83c.47.47.73 1.1.73 1.77V23.5a2.5 2.5 0 0 1-2.5 2.5h-7.94q.1-.09.19-.21.25-.35.25-.79h7.5c.83 0 1.5-.67 1.5-1.5V12h-6.5A2.5 2.5 0 0 1 14 9.5V3zm10 8h6.46a1.5 1.5 0 0 0-.4-.73l-6.83-6.83a1.5 1.5 0 0 0-.73-.4V9.5c0 .83.67 1.5 1.5 1.5M3.17 20.83a3 3 0 0 1 .76 1.24l.5 1.53a.6.6 0 0 0 1.14 0l.5-1.53a3.2 3.2 0 0 1 2-2l1.53-.5a.6.6 0 0 0 0-1.14h-.03l-1.54-.5a3.2 3.2 0 0 1-2-2l-.49-1.53a.6.6 0 0 0-1.14 0l-.5 1.53-.01.04a3.2 3.2 0 0 1-1.96 1.96l-1.53.5a.6.6 0 0 0 0 1.14l1.53.5q.72.23 1.24.76m8.65 3.53.92.3h.02a.36.36 0 0 1 0 .68l-.92.3a1.9 1.9 0 0 0-1.2 1.2l-.3.92a.36.36 0 0 1-.68 0l-.3-.92a1.9 1.9 0 0 0-1.2-1.2l-.92-.3a.36.36 0 0 1 0-.68l.92-.3a1.9 1.9 0 0 0 1.18-1.2l.3-.92a.36.36 0 0 1 .68 0l.3.92a1.9 1.9 0 0 0 1.2 1.2\"/>") { } }
}

#pragma warning restore 1591
