// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable 1591

namespace Microsoft.FluentUI.AspNetCore.Components.Icons.Light;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static partial class Size24
{
    public class Document : Icon { public Document() : base("Document", IconVariant.Light, IconSize.Size24, "<path d=\"M5 4a1 1 0 0 1 1-1h6v5c0 1.1.9 2 2 2h5v10a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4Zm15 5.54a.5.5 0 0 0-.01-.16 2 2 0 0 0-.58-1.17L13.8 2.59A2 2 0 0 0 12.38 2H6a2 2 0 0 0-2 2v16c0 1.1.9 2 2 2h12a2 2 0 0 0 2-2V9.54Zm-7-6.32a1 1 0 0 1 .09.07l5.62 5.62a1 1 0 0 1 .07.09H14a1 1 0 0 1-1-1V3.22Z\"/>") { } }
    public class DocumentSparkle : Icon { public DocumentSparkle() : base("DocumentSparkle", IconVariant.Light, IconSize.Size24, "<path d=\"M6 3a1 1 0 0 0-1 1v6.1a1.5 1.5 0 0 0-1-.03V4c0-1.1.9-2 2-2h6.38a2 2 0 0 1 1.41.59l5.62 5.62A2 2 0 0 1 20 9.62V20a2 2 0 0 1-2 2h-6.12a1.5 1.5 0 0 0-.01-1H18a1 1 0 0 0 1-1V10h-5a2 2 0 0 1-2-2V3H6Zm7.09.3a1 1 0 0 0-.09-.08V8a1 1 0 0 0 1 1h4.78a1 1 0 0 0-.07-.09L13.09 3.3Zm-10 14.11a2.84 2.84 0 0 0-1.35-.95L.36 16a.54.54 0 0 1 0-1.03l1.38-.44a2.84 2.84 0 0 0 1.76-1.77l.01-.03.45-1.38a.54.54 0 0 1 1.03 0l.44 1.38a2.84 2.84 0 0 0 1.8 1.8l1.38.44.03.01a.54.54 0 0 1 0 1.03l-1.38.44a2.84 2.84 0 0 0-1.8 1.8l-.45 1.38a.53.53 0 0 1-.2.26.54.54 0 0 1-.82-.26l-.45-1.38c-.1-.3-.25-.6-.45-.85Zm7.7 3.8-.77-.25a1.58 1.58 0 0 1-1-1l-.25-.76a.3.3 0 0 0-.57 0l-.25.77a1.58 1.58 0 0 1-.98 1l-.77.24a.3.3 0 0 0 0 .57l.77.25a1.58 1.58 0 0 1 1 1l.24.77a.3.3 0 0 0 .58 0l.24-.77a1.58 1.58 0 0 1 1-1l.77-.24a.3.3 0 0 0 0-.57h-.02Z\"/>") { } }
}

#pragma warning restore 1591
