// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable 1591

namespace Microsoft.FluentUI.AspNetCore.Components.Icons.Light;

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static partial class Size48
{
    public class Document : Icon { public Document() : base("Document", IconVariant.Light, IconSize.Size48, "<path d=\"M9 8.25C9 6.45 10.46 5 12.25 5H24v10.75C24 18.1 25.9 20 28.25 20H39v19.75c0 1.8-1.46 3.25-3.25 3.25h-23.5A3.25 3.25 0 0 1 9 39.75V8.25Zm31 11.26a.64.64 0 0 0 0-.04 4.25 4.25 0 0 0-1.24-2.92l-11.3-11.3A4.25 4.25 0 0 0 24.44 4h-12.2A4.25 4.25 0 0 0 8 8.25v31.5C8 42.1 9.9 44 12.25 44h23.5C38.1 44 40 42.1 40 39.75V19.51ZM25 5.05c.66.11 1.27.42 1.74.9l11.3 11.3c.49.48.8 1.1.91 1.75h-10.7A3.25 3.25 0 0 1 25 15.75V5.05Z\"/>") { } }
    public class DocumentSparkle : Icon { public DocumentSparkle() : base("DocumentSparkle", IconVariant.Light, IconSize.Size48, "<path d=\"M12.25 5A3.25 3.25 0 0 0 9 8.25v12.78a3 3 0 0 0-1 .34V8.25C8 5.9 9.9 4 12.25 4H24.53c1.1.02 2.14.47 2.92 1.24l11.3 11.3A4.25 4.25 0 0 1 40 19.48V39.75C40 42.1 38.1 44 35.75 44H23.53c.21-.3.36-.64.42-1h11.8c1.8 0 3.25-1.46 3.25-3.25V20H28.25A4.25 4.25 0 0 1 24 15.75V5H12.25Zm14.5.95a3.25 3.25 0 0 0-1.75-.9v10.7c0 1.8 1.46 3.25 3.25 3.25h10.7a3.25 3.25 0 0 0-.9-1.74l-11.3-11.3ZM6.82 35.11a5.36 5.36 0 0 0-2.54-1.8l-2.6-.85a1.03 1.03 0 0 1 0-1.94l2.6-.84a5.36 5.36 0 0 0 3.32-3.33l.02-.06.85-2.6a1.03 1.03 0 0 1 1.94 0l.84 2.6a5.36 5.36 0 0 0 3.4 3.39l2.6.84.05.02a1.03 1.03 0 0 1 0 1.94l-2.6.84a5.36 5.36 0 0 0-3.4 3.4l-.84 2.6-.03.06a1.03 1.03 0 0 1-1.9-.07l-.86-2.6a5.35 5.35 0 0 0-.85-1.6Zm14.78 6.87-1.38-.44a2.84 2.84 0 0 1-1.8-1.8L18 38.36a.54.54 0 0 0-1.03 0l-.45 1.38a2.84 2.84 0 0 1-1.77 1.8l-1.38.44a.54.54 0 0 0 0 1.03l1.38.45c.15.05.3.11.44.18v.02a2.84 2.84 0 0 1 1.36 1.61l.45 1.38a.54.54 0 0 0 1 .04v-.01a.5.5 0 0 0 .02-.04l.45-1.38a2.84 2.84 0 0 1 1.8-1.8l1.38-.44a.54.54 0 0 0 0-1.03h-.03Z\"/>") { } }
}

#pragma warning restore 1591
