// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable 1591

namespace Microsoft.FluentUI.AspNetCore.Components;

public static partial class Icons
{
    public static partial class Filled
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public static partial class Size10
        {
            public class PresenceAvailable : Icon { public PresenceAvailable() : base("PresenceAvailable", IconVariant.Filled, PresenceAvailableSizeAndContent.Values[0]) { } }
            public class PresenceAway : Icon { public PresenceAway() : base("PresenceAway", IconVariant.Filled, PresenceAwaySizeAndContent.Values[0]) { } }
            public class PresenceBusy : Icon { public PresenceBusy() : base("PresenceBusy", IconVariant.Filled, PresenceBusySizeAndContent.Values[0]) { } }
            public class PresenceDnd : Icon { public PresenceDnd() : base("PresenceDnd", IconVariant.Filled, PresenceDndSizeAndContent.Values[0]) { } }
        }
    }
}

#pragma warning restore 1591
