// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace Microsoft.Fast.Components.FluentUI;

/// <summary />
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static partial class Icons
{
    /// <summary />
    public static IEnumerable<IconInfo> AllIcons
    {
        get
        {
            return GetAllIcons();
        }
    }
}
