// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable 1591

namespace Microsoft.FluentUI.AspNetCore.Components;

public static partial class Icons
{
    /// <summary>
    /// returns the tuple representing the size and content of the first smaller available size
    /// </summary>
    internal static (IconSize size, string content) GetValueForSize(this (IconSize size, string content)[] sizes, int size)
    {
        if (sizes.Length == 0) { new InvalidOperationException($"{nameof(sizes)} must not be empty"); }
        if (sizes.Length == 1) { return sizes[0]; }
        for (int i = sizes.Length - 1; i >= 0; i--)
        {
            if ((int)sizes[i].size <= size) return sizes[i];
        }
        return sizes[0];
    }
}
