// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable 1591

namespace Microsoft.FluentUI.AspNetCore.Components;

public static partial class Icons
{
    public static partial class Regular
    {
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public static partial class Size10
        {
            public class PresenceAvailable : Icon { public PresenceAvailable() : base("PresenceAvailable", IconVariant.Regular, PresenceAvailableSizeAndContent.Values[0]) { } }
            public class PresenceAway : Icon { public PresenceAway() : base("PresenceAway", IconVariant.Regular, PresenceAwaySizeAndContent.Values[0]) { } }
            public class PresenceBlocked : Icon { public PresenceBlocked() : base("PresenceBlocked", IconVariant.Regular, PresenceBlockedSizeAndContent.Values[0]) { } }
            public class PresenceDnd : Icon { public PresenceDnd() : base("PresenceDnd", IconVariant.Regular, PresenceDndSizeAndContent.Values[0]) { } }
            public class PresenceOffline : Icon { public PresenceOffline() : base("PresenceOffline", IconVariant.Regular, PresenceOfflineSizeAndContent.Values[0]) { } }
            public class PresenceOof : Icon { public PresenceOof() : base("PresenceOof", IconVariant.Regular, PresenceOofSizeAndContent.Values[0]) { } }
            public class PresenceUnknown : Icon { public PresenceUnknown() : base("PresenceUnknown", IconVariant.Regular, PresenceUnknownSizeAndContent.Values[0]) { } }
        }
    }
}

#pragma warning restore 1591
