<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>$(NetVersion)</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <AssemblyName>Microsoft.FluentUI.AspNetCore.Components.Tests.Tools</AssemblyName>
    <RootNamespace>Microsoft.FluentUI.AspNetCore.Components.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\Microsoft.FluentUI.AspNetCore.Components.csproj" />
  </ItemGroup>
</Project>
