using System.Text;
using Microsoft.Fast.Components.FluentUI.IconsGenerator.Model;

namespace Microsoft.Fast.Components.FluentUI.IconsGenerator;

internal class EmojisCodeGenerator
{
    private const int MaxEmojiPerClass = int.MaxValue;

    /// <summary>
    /// Initializes a new instance of the <see cref="EmojisCodeGenerator"/> class.
    /// </summary>
    /// <param name="configuration"></param>
    public EmojisCodeGenerator(Configuration configuration)
    {
        Configuration = configuration;
        Logger = (message) => { };
    }

    /// <summary>
    /// Gets or sets the logger.
    /// </summary>
    public Action<string> Logger { get; init; }

    /// <summary>
    /// Gets the configuration.
    /// </summary>
    private Configuration Configuration { get; }

    /// <summary>
    /// Reads all SVG files in the assets folder.
    /// </summary>
    /// <returns></returns>
    public IEnumerable<Model.EmojiFileData> ReadAllAssets()
    {
        const string searchPattern = "metadata.json";
        var emojis = new List<Model.Emoji>();

        Logger.Invoke($"Reading all metadata.json files in {Configuration.AssetsFolder}.");
        var allFiles = Configuration.AssetsFolder.GetFiles(searchPattern, SearchOption.AllDirectories);

        foreach (var file in allFiles)
        {
            var newEmoji = new Model.Emoji(file);
            var key = newEmoji.Key.ToLower();

            emojis.Add(newEmoji);
        }

        return emojis.SelectMany(i => i.Files);
    }

    /// <summary>
    /// Generates all classes for the given emojis.
    /// </summary>
    /// <param name="emojis"></param>
    /// <returns></returns>
    public IEnumerable<FileInfo> GenerateClasses(IEnumerable<Model.EmojiFileData> emojis)
    {
        var generatedFiles = new List<FileInfo>();
        var allGroups = emojis.Select(i => i.Emoji.Group)
                              .Distinct()
                              .OrderBy(i => i);
        var allStyles = emojis.Select(file => file.Style)
                              .Distinct()
                              .OrderBy(i => i);
        var allSkinTones = emojis.Select(file => file.SkinTone)
                              .Distinct()
                              .OrderBy(i => i);

        // Delete previous files
        foreach (var file in Configuration.TargetFolder.GetFiles("*.cs", SearchOption.TopDirectoryOnly))
        {
            file.Delete();
        }

        // Generate all classes
        foreach (var group in allGroups)
        {
            foreach (var style in allStyles)
            {
                foreach (var skintone in allSkinTones)
                {
                    // CSharp
                    var emojisForFile = emojis.Where(i => i.Emoji.Group == group
                                                       && i.Style == style
                                                       && i.SkinTone == skintone)
                                                    .OrderBy(i => i.Emoji.Name);

                    if (emojisForFile.Any() == false)
                    {
                        continue;
                    }

                    int part = 0;
                    var emojisParts = Tools.Split(emojisForFile, MaxEmojiPerClass);
                    foreach (var emojisPart in emojisParts)
                    {
                        var filename = emojisParts.Count() == 1
                                     ? $"{group}-{style}-{skintone}.cs"
                                     : $"{group}-{style}-{skintone}-{part}.cs";
                        var file = new FileInfo(Path.Combine(Configuration.TargetFolder.FullName, filename));

                        Logger.Invoke($"Generating {file.Name}, containing {emojisPart.Count()} emojis.");
                        var classContent = GenerateClass(group, style, skintone, emojisPart);

                        File.WriteAllText(file.FullName, classContent);
                        generatedFiles.Add(file);

                        part++;
                    }
                }
            }
        }

        return generatedFiles;
    }

    /// <summary />
    private string GenerateClass(string group, string style, string skintone, IEnumerable<Model.EmojiFileData> emojis)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("//     This code was generated by a tool.");
        builder.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        builder.AppendLine("//     the code is regenerated.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#pragma warning disable 1591");
        builder.AppendLine();
        builder.AppendLine("namespace " + Configuration.Namespace + ";");
        builder.AppendLine();
        builder.AppendLine("public static partial class Emojis");
        builder.AppendLine("{");
        builder.AppendLine("    public static partial class " + group);
        builder.AppendLine("    {");
        builder.AppendLine("        public static partial class " + style);
        builder.AppendLine("        {");
        builder.AppendLine("            public static partial class " + skintone);
        builder.AppendLine("            {");

        foreach (var file in emojis)
        {
            AddProperties(builder, file);
        }

        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("#pragma warning restore 1591");

        return builder.ToString();
    }

    private void AddProperties(StringBuilder builder, EmojiFileData file, int indentation = 16)
    {
        string indentationString = new string(' ', indentation);

        var content = file.GetContent(removeSvgRoot: true);
        var size = content.Size.Width;
        var svgContent = content.Content;
        var group = Tools.ToPascalCase(file.Emoji.Meta.Group, "_");
        var svgZipped = String.Join(", ", Tools.Zip(svgContent).Select(i => Convert.ToString(i)));
        var svgBytes = $"new byte [] {{ {svgZipped} }}";

        builder.AppendLine($"{indentationString}public class {file.Emoji.Name} : Emoji {{ public {file.Emoji.Name}() : base(\"{file.Emoji.Name}\", EmojiSize.Size{size}, EmojiGroup.{group}, EmojiSkintone.{file.SkinTone}, EmojiStyle.{file.Style}, {svgBytes}) {{ }} }}");
    }
}
