using System.Text;

namespace Microsoft.Fast.Components.FluentUI.IconsGenerator;

internal class EmojisCodeGenerator
{
    /// <summary>
    /// Initializes a new instance of the <see cref="EmojisCodeGenerator"/> class.
    /// </summary>
    /// <param name="configuration"></param>
    public EmojisCodeGenerator(Configuration configuration)
    {
        Configuration = configuration;
        Logger = (message) => { };
    }

    /// <summary>
    /// Gets or sets the logger.
    /// </summary>
    public Action<string> Logger { get; init; }

    /// <summary>
    /// Gets the configuration.
    /// </summary>
    private Configuration Configuration { get; }

    /// <summary>
    /// Reads all SVG files in the assets folder.
    /// </summary>
    /// <returns></returns>
    public IEnumerable<Model.Emoji> ReadAllAssets()
    {
        const string searchPattern = "metadata.json";
        var emojis = new Dictionary<string, Model.Emoji>();

        Logger.Invoke($"Reading all metadata.json files in {Configuration.AssetsFolder}.");
        var allFiles = Configuration.AssetsFolder.GetFiles(searchPattern, SearchOption.AllDirectories);

        foreach (var file in allFiles)
        {
            var newEmoji = new Model.Emoji(file);
            var key = newEmoji.Key.ToLower();

            if (!emojis.ContainsKey(key))
            {
                emojis.Add(newEmoji.Key.ToLower(), newEmoji);
            }
        }

        return emojis.Values
                     .OrderBy(i => i.Group)
                     .ThenBy(i => i.Name)
                     .ToArray();
    }

    /// <summary />
    private string GenerateClass(int size, string variant, IEnumerable<Model.Icon> icons)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("//     This code was generated by a tool.");
        builder.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        builder.AppendLine("//     the code is regenerated.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#pragma warning disable 1591");
        builder.AppendLine();
        builder.AppendLine("namespace " + Configuration.Namespace + ";");
        builder.AppendLine();
        builder.AppendLine("public static partial class Icons");
        builder.AppendLine("{");
        builder.AppendLine("    public static partial class " + variant);
        builder.AppendLine("    {");
        builder.AppendLine("        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        builder.AppendLine("        public static partial class Size" + size);
        builder.AppendLine("        {");

        //AddProperties(builder, icons);

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("#pragma warning restore 1591");

        return builder.ToString();
    }
}
