// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace Microsoft.Fast.Components.FluentUI;

/// <summary />
public static partial class Icons
{
    /// <summary />
    public static partial class Regular
    {
        /// <summary />
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public static partial class Size32
        {
            private static System.Resources.ResourceManager _resourceMananager;

            /// <summary>
            /// Returns the cached ResourceManager instance used by this class.
            /// </summary>
            [System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            internal static System.Resources.ResourceManager ResourceManager
            {
                get
                {
                    if (_resourceMananager == null)
                    {
                        _resourceMananager = new System.Resources.ResourceManager("Microsoft.Fast.Components.FluentUI.Icons.Assets.Regular32Data", typeof(Icons).Assembly);
                    }

                    return _resourceMananager;
                }
            }

            /// <summary />
            public static string Accessibility { get; } = ResourceManager.GetString("Accessibility");

            /// <summary />
            public static string AccessibilityCheckmark { get; } = ResourceManager.GetString("AccessibilityCheckmark");

            /// <summary />
            public static string AddCircle { get; } = ResourceManager.GetString("AddCircle");

            /// <summary />
            public static string Alert { get; } = ResourceManager.GetString("Alert");

            /// <summary />
            public static string AlignBottom { get; } = ResourceManager.GetString("AlignBottom");

            /// <summary />
            public static string AlignCenterHorizontal { get; } = ResourceManager.GetString("AlignCenterHorizontal");

            /// <summary />
            public static string AlignCenterVertical { get; } = ResourceManager.GetString("AlignCenterVertical");

            /// <summary />
            public static string AlignLeft { get; } = ResourceManager.GetString("AlignLeft");

            /// <summary />
            public static string AlignRight { get; } = ResourceManager.GetString("AlignRight");

            /// <summary />
            public static string AlignTop { get; } = ResourceManager.GetString("AlignTop");

            /// <summary />
            public static string AnimalRabbit { get; } = ResourceManager.GetString("AnimalRabbit");

            /// <summary />
            public static string AnimalRabbitOff { get; } = ResourceManager.GetString("AnimalRabbitOff");

            /// <summary />
            public static string AppFolder { get; } = ResourceManager.GetString("AppFolder");

            /// <summary />
            public static string AppGeneric { get; } = ResourceManager.GetString("AppGeneric");

            /// <summary />
            public static string ApprovalsApp { get; } = ResourceManager.GetString("ApprovalsApp");

            /// <summary />
            public static string Apps { get; } = ResourceManager.GetString("Apps");

            /// <summary />
            public static string Archive { get; } = ResourceManager.GetString("Archive");

            /// <summary />
            public static string ArchiveArrowBack { get; } = ResourceManager.GetString("ArchiveArrowBack");

            /// <summary />
            public static string ArrowCircleDown { get; } = ResourceManager.GetString("ArrowCircleDown");

            /// <summary />
            public static string ArrowCircleLeft { get; } = ResourceManager.GetString("ArrowCircleLeft");

            /// <summary />
            public static string ArrowCircleRight { get; } = ResourceManager.GetString("ArrowCircleRight");

            /// <summary />
            public static string ArrowCircleUp { get; } = ResourceManager.GetString("ArrowCircleUp");

            /// <summary />
            public static string ArrowClockwise { get; } = ResourceManager.GetString("ArrowClockwise");

            /// <summary />
            public static string ArrowCounterclockwise { get; } = ResourceManager.GetString("ArrowCounterclockwise");

            /// <summary />
            public static string ArrowDown { get; } = ResourceManager.GetString("ArrowDown");

            /// <summary />
            public static string ArrowDownLeft { get; } = ResourceManager.GetString("ArrowDownLeft");

            /// <summary />
            public static string ArrowFlowDiagonalUpRight { get; } = ResourceManager.GetString("ArrowFlowDiagonalUpRight");

            /// <summary />
            public static string ArrowFlowUpRight { get; } = ResourceManager.GetString("ArrowFlowUpRight");

            /// <summary />
            public static string ArrowLeft { get; } = ResourceManager.GetString("ArrowLeft");

            /// <summary />
            public static string ArrowMaximize { get; } = ResourceManager.GetString("ArrowMaximize");

            /// <summary />
            public static string ArrowOutlineUpRight { get; } = ResourceManager.GetString("ArrowOutlineUpRight");

            /// <summary />
            public static string ArrowRedo { get; } = ResourceManager.GetString("ArrowRedo");

            /// <summary />
            public static string ArrowRedoTempLtr { get; } = ResourceManager.GetString("ArrowRedoTempLtr");

            /// <summary />
            public static string ArrowRedoTempRtl { get; } = ResourceManager.GetString("ArrowRedoTempRtl");

            /// <summary />
            public static string ArrowReset { get; } = ResourceManager.GetString("ArrowReset");

            /// <summary />
            public static string ArrowRight { get; } = ResourceManager.GetString("ArrowRight");

            /// <summary />
            public static string ArrowShuffle { get; } = ResourceManager.GetString("ArrowShuffle");

            /// <summary />
            public static string ArrowShuffleOff { get; } = ResourceManager.GetString("ArrowShuffleOff");

            /// <summary />
            public static string ArrowUndo { get; } = ResourceManager.GetString("ArrowUndo");

            /// <summary />
            public static string ArrowUndoTempLtr { get; } = ResourceManager.GetString("ArrowUndoTempLtr");

            /// <summary />
            public static string ArrowUndoTempRtl { get; } = ResourceManager.GetString("ArrowUndoTempRtl");

            /// <summary />
            public static string ArrowUp { get; } = ResourceManager.GetString("ArrowUp");

            /// <summary />
            public static string ArrowUpRight { get; } = ResourceManager.GetString("ArrowUpRight");

            /// <summary />
            public static string AssetsAdd { get; } = ResourceManager.GetString("AssetsAdd");

            /// <summary />
            public static string AssetsEye { get; } = ResourceManager.GetString("AssetsEye");

            /// <summary />
            public static string AssetsKey { get; } = ResourceManager.GetString("AssetsKey");

            /// <summary />
            public static string AssetsMic { get; } = ResourceManager.GetString("AssetsMic");

            /// <summary />
            public static string AssetsPen { get; } = ResourceManager.GetString("AssetsPen");

            /// <summary />
            public static string AssetsPin { get; } = ResourceManager.GetString("AssetsPin");

            /// <summary />
            public static string AssetsTag { get; } = ResourceManager.GetString("AssetsTag");

            /// <summary />
            public static string Backpack { get; } = ResourceManager.GetString("Backpack");

            /// <summary />
            public static string Beach { get; } = ResourceManager.GetString("Beach");

            /// <summary />
            public static string Beaker { get; } = ResourceManager.GetString("Beaker");

            /// <summary />
            public static string BeakerOff { get; } = ResourceManager.GetString("BeakerOff");

            /// <summary />
            public static string BinderTriangle { get; } = ResourceManager.GetString("BinderTriangle");

            /// <summary />
            public static string Bluetooth { get; } = ResourceManager.GetString("Bluetooth");

            /// <summary />
            public static string BookContacts { get; } = ResourceManager.GetString("BookContacts");

            /// <summary />
            public static string Bookmark { get; } = ResourceManager.GetString("Bookmark");

            /// <summary />
            public static string BookmarkMultiple { get; } = ResourceManager.GetString("BookmarkMultiple");

            /// <summary />
            public static string BookOpen { get; } = ResourceManager.GetString("BookOpen");

            /// <summary />
            public static string BookOpenMicrophone { get; } = ResourceManager.GetString("BookOpenMicrophone");

            /// <summary />
            public static string Braces { get; } = ResourceManager.GetString("Braces");

            /// <summary />
            public static string BranchFork { get; } = ResourceManager.GetString("BranchFork");

            /// <summary />
            public static string Briefcase { get; } = ResourceManager.GetString("Briefcase");

            /// <summary />
            public static string BriefcaseMedical { get; } = ResourceManager.GetString("BriefcaseMedical");

            /// <summary />
            public static string BriefcaseOff { get; } = ResourceManager.GetString("BriefcaseOff");

            /// <summary />
            public static string BrightnessHigh { get; } = ResourceManager.GetString("BrightnessHigh");

            /// <summary />
            public static string BrightnessLow { get; } = ResourceManager.GetString("BrightnessLow");

            /// <summary />
            public static string Building { get; } = ResourceManager.GetString("Building");

            /// <summary />
            public static string BuildingFactory { get; } = ResourceManager.GetString("BuildingFactory");

            /// <summary />
            public static string BuildingGovernment { get; } = ResourceManager.GetString("BuildingGovernment");

            /// <summary />
            public static string BuildingRetailMore { get; } = ResourceManager.GetString("BuildingRetailMore");

            /// <summary />
            public static string BuildingTownhouse { get; } = ResourceManager.GetString("BuildingTownhouse");

            /// <summary />
            public static string CalendarArrowCounterclockwise { get; } = ResourceManager.GetString("CalendarArrowCounterclockwise");

            /// <summary />
            public static string CalendarEmpty { get; } = ResourceManager.GetString("CalendarEmpty");

            /// <summary />
            public static string CalendarLock { get; } = ResourceManager.GetString("CalendarLock");

            /// <summary />
            public static string CalendarLtr { get; } = ResourceManager.GetString("CalendarLtr");

            /// <summary />
            public static string CalendarMonth { get; } = ResourceManager.GetString("CalendarMonth");

            /// <summary />
            public static string CalendarMultiple { get; } = ResourceManager.GetString("CalendarMultiple");

            /// <summary />
            public static string CalendarRtl { get; } = ResourceManager.GetString("CalendarRtl");

            /// <summary />
            public static string CalendarSettings { get; } = ResourceManager.GetString("CalendarSettings");

            /// <summary />
            public static string CalendarShield { get; } = ResourceManager.GetString("CalendarShield");

            /// <summary />
            public static string Call { get; } = ResourceManager.GetString("Call");

            /// <summary />
            public static string CallForward { get; } = ResourceManager.GetString("CallForward");

            /// <summary />
            public static string CallPark { get; } = ResourceManager.GetString("CallPark");

            /// <summary />
            public static string CallTransfer { get; } = ResourceManager.GetString("CallTransfer");

            /// <summary />
            public static string Chat { get; } = ResourceManager.GetString("Chat");

            /// <summary />
            public static string ChatAdd { get; } = ResourceManager.GetString("ChatAdd");

            /// <summary />
            public static string ChatBubblesQuestion { get; } = ResourceManager.GetString("ChatBubblesQuestion");

            /// <summary />
            public static string ChatEmpty { get; } = ResourceManager.GetString("ChatEmpty");

            /// <summary />
            public static string ChatMultiple { get; } = ResourceManager.GetString("ChatMultiple");

            /// <summary />
            public static string ChatMultipleHeart { get; } = ResourceManager.GetString("ChatMultipleHeart");

            /// <summary />
            public static string ChatSparkle { get; } = ResourceManager.GetString("ChatSparkle");

            /// <summary />
            public static string Checkmark { get; } = ResourceManager.GetString("Checkmark");

            /// <summary />
            public static string CheckmarkCircle { get; } = ResourceManager.GetString("CheckmarkCircle");

            /// <summary />
            public static string ChevronCircleDown { get; } = ResourceManager.GetString("ChevronCircleDown");

            /// <summary />
            public static string ChevronCircleLeft { get; } = ResourceManager.GetString("ChevronCircleLeft");

            /// <summary />
            public static string ChevronCircleRight { get; } = ResourceManager.GetString("ChevronCircleRight");

            /// <summary />
            public static string ChevronCircleUp { get; } = ResourceManager.GetString("ChevronCircleUp");

            /// <summary />
            public static string Circle { get; } = ResourceManager.GetString("Circle");

            /// <summary />
            public static string Clipboard { get; } = ResourceManager.GetString("Clipboard");

            /// <summary />
            public static string ClipboardDataBar { get; } = ResourceManager.GetString("ClipboardDataBar");

            /// <summary />
            public static string ClipboardText { get; } = ResourceManager.GetString("ClipboardText");

            /// <summary />
            public static string ClipboardTextEdit { get; } = ResourceManager.GetString("ClipboardTextEdit");

            /// <summary />
            public static string ClipboardTextLtr { get; } = ResourceManager.GetString("ClipboardTextLtr");

            /// <summary />
            public static string Clock { get; } = ResourceManager.GetString("Clock");

            /// <summary />
            public static string ClockAlarm { get; } = ResourceManager.GetString("ClockAlarm");

            /// <summary />
            public static string ClosedCaption { get; } = ResourceManager.GetString("ClosedCaption");

            /// <summary />
            public static string Cloud { get; } = ResourceManager.GetString("Cloud");

            /// <summary />
            public static string CloudArchive { get; } = ResourceManager.GetString("CloudArchive");

            /// <summary />
            public static string CloudArrowDown { get; } = ResourceManager.GetString("CloudArrowDown");

            /// <summary />
            public static string CloudArrowUp { get; } = ResourceManager.GetString("CloudArrowUp");

            /// <summary />
            public static string CloudCheckmark { get; } = ResourceManager.GetString("CloudCheckmark");

            /// <summary />
            public static string CloudDismiss { get; } = ResourceManager.GetString("CloudDismiss");

            /// <summary />
            public static string CloudError { get; } = ResourceManager.GetString("CloudError");

            /// <summary />
            public static string CloudOff { get; } = ResourceManager.GetString("CloudOff");

            /// <summary />
            public static string CloudSync { get; } = ResourceManager.GetString("CloudSync");

            /// <summary />
            public static string CloudWords { get; } = ResourceManager.GetString("CloudWords");

            /// <summary />
            public static string Clover { get; } = ResourceManager.GetString("Clover");

            /// <summary />
            public static string CodeBlock { get; } = ResourceManager.GetString("CodeBlock");

            /// <summary />
            public static string CodeCircle { get; } = ResourceManager.GetString("CodeCircle");

            /// <summary />
            public static string CommentMultiple { get; } = ResourceManager.GetString("CommentMultiple");

            /// <summary />
            public static string CommentMultipleLink { get; } = ResourceManager.GetString("CommentMultipleLink");

            /// <summary />
            public static string ContactCard { get; } = ResourceManager.GetString("ContactCard");

            /// <summary />
            public static string ContactCardRibbon { get; } = ResourceManager.GetString("ContactCardRibbon");

            /// <summary />
            public static string ContentSettings { get; } = ResourceManager.GetString("ContentSettings");

            /// <summary />
            public static string ContentView { get; } = ResourceManager.GetString("ContentView");

            /// <summary />
            public static string ContractDownLeft { get; } = ResourceManager.GetString("ContractDownLeft");

            /// <summary />
            public static string Copy { get; } = ResourceManager.GetString("Copy");

            /// <summary />
            public static string Couch { get; } = ResourceManager.GetString("Couch");

            /// <summary />
            public static string CreditCardClock { get; } = ResourceManager.GetString("CreditCardClock");

            /// <summary />
            public static string Crop { get; } = ResourceManager.GetString("Crop");

            /// <summary />
            public static string Cube { get; } = ResourceManager.GetString("Cube");

            /// <summary />
            public static string CursorHover { get; } = ResourceManager.GetString("CursorHover");

            /// <summary />
            public static string DataBarVertical { get; } = ResourceManager.GetString("DataBarVertical");

            /// <summary />
            public static string DataBarVerticalStar { get; } = ResourceManager.GetString("DataBarVerticalStar");

            /// <summary />
            public static string Database { get; } = ResourceManager.GetString("Database");

            /// <summary />
            public static string DatabaseArrowRight { get; } = ResourceManager.GetString("DatabaseArrowRight");

            /// <summary />
            public static string DatabaseMultiple { get; } = ResourceManager.GetString("DatabaseMultiple");

            /// <summary />
            public static string DataTrending { get; } = ResourceManager.GetString("DataTrending");

            /// <summary />
            public static string Delete { get; } = ResourceManager.GetString("Delete");

            /// <summary />
            public static string Desktop { get; } = ResourceManager.GetString("Desktop");

            /// <summary />
            public static string DesktopMac { get; } = ResourceManager.GetString("DesktopMac");

            /// <summary />
            public static string DesktopPulse { get; } = ResourceManager.GetString("DesktopPulse");

            /// <summary />
            public static string DeviceMeetingRoom { get; } = ResourceManager.GetString("DeviceMeetingRoom");

            /// <summary />
            public static string DeviceMeetingRoomRemote { get; } = ResourceManager.GetString("DeviceMeetingRoomRemote");

            /// <summary />
            public static string Dialpad { get; } = ResourceManager.GetString("Dialpad");

            /// <summary />
            public static string Diamond { get; } = ResourceManager.GetString("Diamond");

            /// <summary />
            public static string Dishwasher { get; } = ResourceManager.GetString("Dishwasher");

            /// <summary />
            public static string Dismiss { get; } = ResourceManager.GetString("Dismiss");

            /// <summary />
            public static string DismissCircle { get; } = ResourceManager.GetString("DismissCircle");

            /// <summary />
            public static string Document { get; } = ResourceManager.GetString("Document");

            /// <summary />
            public static string DocumentBorder { get; } = ResourceManager.GetString("DocumentBorder");

            /// <summary />
            public static string DocumentBorderPrint { get; } = ResourceManager.GetString("DocumentBorderPrint");

            /// <summary />
            public static string DocumentData { get; } = ResourceManager.GetString("DocumentData");

            /// <summary />
            public static string DocumentDataLink { get; } = ResourceManager.GetString("DocumentDataLink");

            /// <summary />
            public static string DocumentLock { get; } = ResourceManager.GetString("DocumentLock");

            /// <summary />
            public static string DocumentPdf { get; } = ResourceManager.GetString("DocumentPdf");

            /// <summary />
            public static string DocumentPrint { get; } = ResourceManager.GetString("DocumentPrint");

            /// <summary />
            public static string DocumentRibbon { get; } = ResourceManager.GetString("DocumentRibbon");

            /// <summary />
            public static string DocumentSync { get; } = ResourceManager.GetString("DocumentSync");

            /// <summary />
            public static string DrinkBottle { get; } = ResourceManager.GetString("DrinkBottle");

            /// <summary />
            public static string DrinkBottleOff { get; } = ResourceManager.GetString("DrinkBottleOff");

            /// <summary />
            public static string Earth { get; } = ResourceManager.GetString("Earth");

            /// <summary />
            public static string EarthLeaf { get; } = ResourceManager.GetString("EarthLeaf");

            /// <summary />
            public static string Edit { get; } = ResourceManager.GetString("Edit");

            /// <summary />
            public static string EditOff { get; } = ResourceManager.GetString("EditOff");

            /// <summary />
            public static string EditProhibited { get; } = ResourceManager.GetString("EditProhibited");

            /// <summary />
            public static string Elevator { get; } = ResourceManager.GetString("Elevator");

            /// <summary />
            public static string Emoji { get; } = ResourceManager.GetString("Emoji");

            /// <summary />
            public static string EmojiHand { get; } = ResourceManager.GetString("EmojiHand");

            /// <summary />
            public static string EmojiHint { get; } = ResourceManager.GetString("EmojiHint");

            /// <summary />
            public static string EmojiSparkle { get; } = ResourceManager.GetString("EmojiSparkle");

            /// <summary />
            public static string ExpandUpLeft { get; } = ResourceManager.GetString("ExpandUpLeft");

            /// <summary />
            public static string ExpandUpRight { get; } = ResourceManager.GetString("ExpandUpRight");

            /// <summary />
            public static string EyeLines { get; } = ResourceManager.GetString("EyeLines");

            /// <summary />
            public static string Feed { get; } = ResourceManager.GetString("Feed");

            /// <summary />
            public static string Filmstrip { get; } = ResourceManager.GetString("Filmstrip");

            /// <summary />
            public static string FilmstripPlay { get; } = ResourceManager.GetString("FilmstripPlay");

            /// <summary />
            public static string FilmstripSplit { get; } = ResourceManager.GetString("FilmstripSplit");

            /// <summary />
            public static string Fireplace { get; } = ResourceManager.GetString("Fireplace");

            /// <summary />
            public static string Flag { get; } = ResourceManager.GetString("Flag");

            /// <summary />
            public static string FlagClock { get; } = ResourceManager.GetString("FlagClock");

            /// <summary />
            public static string Flash { get; } = ResourceManager.GetString("Flash");

            /// <summary />
            public static string FlipHorizontal { get; } = ResourceManager.GetString("FlipHorizontal");

            /// <summary />
            public static string FlipVertical { get; } = ResourceManager.GetString("FlipVertical");

            /// <summary />
            public static string Flow { get; } = ResourceManager.GetString("Flow");

            /// <summary />
            public static string Fluent { get; } = ResourceManager.GetString("Fluent");

            /// <summary />
            public static string Folder { get; } = ResourceManager.GetString("Folder");

            /// <summary />
            public static string FolderArrowLeft { get; } = ResourceManager.GetString("FolderArrowLeft");

            /// <summary />
            public static string FoodChickenLeg { get; } = ResourceManager.GetString("FoodChickenLeg");

            /// <summary />
            public static string Games { get; } = ResourceManager.GetString("Games");

            /// <summary />
            public static string Gauge { get; } = ResourceManager.GetString("Gauge");

            /// <summary />
            public static string Gavel { get; } = ResourceManager.GetString("Gavel");

            /// <summary />
            public static string Glasses { get; } = ResourceManager.GetString("Glasses");

            /// <summary />
            public static string GlassesOff { get; } = ResourceManager.GetString("GlassesOff");

            /// <summary />
            public static string Globe { get; } = ResourceManager.GetString("Globe");

            /// <summary />
            public static string GlobeSurface { get; } = ResourceManager.GetString("GlobeSurface");

            /// <summary />
            public static string GlobeVideo { get; } = ResourceManager.GetString("GlobeVideo");

            /// <summary />
            public static string HandOpenHeart { get; } = ResourceManager.GetString("HandOpenHeart");

            /// <summary />
            public static string Handshake { get; } = ResourceManager.GetString("Handshake");

            /// <summary />
            public static string Headphones { get; } = ResourceManager.GetString("Headphones");

            /// <summary />
            public static string HeadphonesSoundWave { get; } = ResourceManager.GetString("HeadphonesSoundWave");

            /// <summary />
            public static string Headset { get; } = ResourceManager.GetString("Headset");

            /// <summary />
            public static string Heart { get; } = ResourceManager.GetString("Heart");

            /// <summary />
            public static string HeartCircleHint { get; } = ResourceManager.GetString("HeartCircleHint");

            /// <summary />
            public static string HeartPulse { get; } = ResourceManager.GetString("HeartPulse");

            /// <summary />
            public static string History { get; } = ResourceManager.GetString("History");

            /// <summary />
            public static string HistoryDismiss { get; } = ResourceManager.GetString("HistoryDismiss");

            /// <summary />
            public static string Home { get; } = ResourceManager.GetString("Home");

            /// <summary />
            public static string HomeDatabase { get; } = ResourceManager.GetString("HomeDatabase");

            /// <summary />
            public static string HomeHeart { get; } = ResourceManager.GetString("HomeHeart");

            /// <summary />
            public static string HomeMore { get; } = ResourceManager.GetString("HomeMore");

            /// <summary />
            public static string HomeSplit { get; } = ResourceManager.GetString("HomeSplit");

            /// <summary />
            public static string Image { get; } = ResourceManager.GetString("Image");

            /// <summary />
            public static string ImageBorder { get; } = ResourceManager.GetString("ImageBorder");

            /// <summary />
            public static string ImageCircle { get; } = ResourceManager.GetString("ImageCircle");

            /// <summary />
            public static string ImageMultiple { get; } = ResourceManager.GetString("ImageMultiple");

            /// <summary />
            public static string ImageOff { get; } = ResourceManager.GetString("ImageOff");

            /// <summary />
            public static string ImageTable { get; } = ResourceManager.GetString("ImageTable");

            /// <summary />
            public static string Info { get; } = ResourceManager.GetString("Info");

            /// <summary />
            public static string InkingTool { get; } = ResourceManager.GetString("InkingTool");

            /// <summary />
            public static string LeafOne { get; } = ResourceManager.GetString("LeafOne");

            /// <summary />
            public static string LeafTwo { get; } = ResourceManager.GetString("LeafTwo");

            /// <summary />
            public static string Lightbulb { get; } = ResourceManager.GetString("Lightbulb");

            /// <summary />
            public static string LightbulbPerson { get; } = ResourceManager.GetString("LightbulbPerson");

            /// <summary />
            public static string Line { get; } = ResourceManager.GetString("Line");

            /// <summary />
            public static string LineDashes { get; } = ResourceManager.GetString("LineDashes");

            /// <summary />
            public static string Link { get; } = ResourceManager.GetString("Link");

            /// <summary />
            public static string LocationArrow { get; } = ResourceManager.GetString("LocationArrow");

            /// <summary />
            public static string LockClosed { get; } = ResourceManager.GetString("LockClosed");

            /// <summary />
            public static string Luggage { get; } = ResourceManager.GetString("Luggage");

            /// <summary />
            public static string MailReadMultiple { get; } = ResourceManager.GetString("MailReadMultiple");

            /// <summary />
            public static string MathFormula { get; } = ResourceManager.GetString("MathFormula");

            /// <summary />
            public static string MathSymbols { get; } = ResourceManager.GetString("MathSymbols");

            /// <summary />
            public static string MeetNow { get; } = ResourceManager.GetString("MeetNow");

            /// <summary />
            public static string MegaphoneLoud { get; } = ResourceManager.GetString("MegaphoneLoud");

            /// <summary />
            public static string Mention { get; } = ResourceManager.GetString("Mention");

            /// <summary />
            public static string MicOff { get; } = ResourceManager.GetString("MicOff");

            /// <summary />
            public static string MicPulse { get; } = ResourceManager.GetString("MicPulse");

            /// <summary />
            public static string MicPulseOff { get; } = ResourceManager.GetString("MicPulseOff");

            /// <summary />
            public static string Molecule { get; } = ResourceManager.GetString("Molecule");

            /// <summary />
            public static string MoreCircle { get; } = ResourceManager.GetString("MoreCircle");

            /// <summary />
            public static string MoreHorizontal { get; } = ResourceManager.GetString("MoreHorizontal");

            /// <summary />
            public static string MoreVertical { get; } = ResourceManager.GetString("MoreVertical");

            /// <summary />
            public static string Multiplier12x { get; } = ResourceManager.GetString("Multiplier12x");

            /// <summary />
            public static string Multiplier15x { get; } = ResourceManager.GetString("Multiplier15x");

            /// <summary />
            public static string Multiplier18x { get; } = ResourceManager.GetString("Multiplier18x");

            /// <summary />
            public static string Multiplier1x { get; } = ResourceManager.GetString("Multiplier1x");

            /// <summary />
            public static string Multiplier2x { get; } = ResourceManager.GetString("Multiplier2x");

            /// <summary />
            public static string Multiplier5x { get; } = ResourceManager.GetString("Multiplier5x");

            /// <summary />
            public static string Next { get; } = ResourceManager.GetString("Next");

            /// <summary />
            public static string Notebook { get; } = ResourceManager.GetString("Notebook");

            /// <summary />
            public static string Notepad { get; } = ResourceManager.GetString("Notepad");

            /// <summary />
            public static string NumberSymbol { get; } = ResourceManager.GetString("NumberSymbol");

            /// <summary />
            public static string Open { get; } = ResourceManager.GetString("Open");

            /// <summary />
            public static string Organization { get; } = ResourceManager.GetString("Organization");

            /// <summary />
            public static string Oval { get; } = ResourceManager.GetString("Oval");

            /// <summary />
            public static string Oven { get; } = ResourceManager.GetString("Oven");

            /// <summary />
            public static string PanelLeft { get; } = ResourceManager.GetString("PanelLeft");

            /// <summary />
            public static string PanelLeftAdd { get; } = ResourceManager.GetString("PanelLeftAdd");

            /// <summary />
            public static string PanelLeftHeader { get; } = ResourceManager.GetString("PanelLeftHeader");

            /// <summary />
            public static string PanelLeftHeaderAdd { get; } = ResourceManager.GetString("PanelLeftHeaderAdd");

            /// <summary />
            public static string PanelLeftText { get; } = ResourceManager.GetString("PanelLeftText");

            /// <summary />
            public static string PanelLeftTextAdd { get; } = ResourceManager.GetString("PanelLeftTextAdd");

            /// <summary />
            public static string PanelLeftTextDismiss { get; } = ResourceManager.GetString("PanelLeftTextDismiss");

            /// <summary />
            public static string PanelRight { get; } = ResourceManager.GetString("PanelRight");

            /// <summary />
            public static string Patient { get; } = ResourceManager.GetString("Patient");

            /// <summary />
            public static string Pause { get; } = ResourceManager.GetString("Pause");

            /// <summary />
            public static string Payment { get; } = ResourceManager.GetString("Payment");

            /// <summary />
            public static string PenDismiss { get; } = ResourceManager.GetString("PenDismiss");

            /// <summary />
            public static string PenOff { get; } = ResourceManager.GetString("PenOff");

            /// <summary />
            public static string PenProhibited { get; } = ResourceManager.GetString("PenProhibited");

            /// <summary />
            public static string Pentagon { get; } = ResourceManager.GetString("Pentagon");

            /// <summary />
            public static string People { get; } = ResourceManager.GetString("People");

            /// <summary />
            public static string PeopleCommunity { get; } = ResourceManager.GetString("PeopleCommunity");

            /// <summary />
            public static string PeopleStar { get; } = ResourceManager.GetString("PeopleStar");

            /// <summary />
            public static string PeopleTeam { get; } = ResourceManager.GetString("PeopleTeam");

            /// <summary />
            public static string PeopleTeamDelete { get; } = ResourceManager.GetString("PeopleTeamDelete");

            /// <summary />
            public static string Person { get; } = ResourceManager.GetString("Person");

            /// <summary />
            public static string Person5 { get; } = ResourceManager.GetString("Person5");

            /// <summary />
            public static string Person6 { get; } = ResourceManager.GetString("Person6");

            /// <summary />
            public static string PersonArrowBack { get; } = ResourceManager.GetString("PersonArrowBack");

            /// <summary />
            public static string PersonBoard { get; } = ResourceManager.GetString("PersonBoard");

            /// <summary />
            public static string PersonCircle { get; } = ResourceManager.GetString("PersonCircle");

            /// <summary />
            public static string PersonFeedback { get; } = ResourceManager.GetString("PersonFeedback");

            /// <summary />
            public static string PersonLink { get; } = ResourceManager.GetString("PersonLink");

            /// <summary />
            public static string PersonSearch { get; } = ResourceManager.GetString("PersonSearch");

            /// <summary />
            public static string PersonStar { get; } = ResourceManager.GetString("PersonStar");

            /// <summary />
            public static string PersonSync { get; } = ResourceManager.GetString("PersonSync");

            /// <summary />
            public static string PersonTag { get; } = ResourceManager.GetString("PersonTag");

            /// <summary />
            public static string Phone { get; } = ResourceManager.GetString("Phone");

            /// <summary />
            public static string PhoneDesktop { get; } = ResourceManager.GetString("PhoneDesktop");

            /// <summary />
            public static string PhoneLaptop { get; } = ResourceManager.GetString("PhoneLaptop");

            /// <summary />
            public static string PinOff { get; } = ResourceManager.GetString("PinOff");

            /// <summary />
            public static string Pipeline { get; } = ResourceManager.GetString("Pipeline");

            /// <summary />
            public static string PipelineAdd { get; } = ResourceManager.GetString("PipelineAdd");

            /// <summary />
            public static string Play { get; } = ResourceManager.GetString("Play");

            /// <summary />
            public static string Premium { get; } = ResourceManager.GetString("Premium");

            /// <summary />
            public static string Previous { get; } = ResourceManager.GetString("Previous");

            /// <summary />
            public static string Print { get; } = ResourceManager.GetString("Print");

            /// <summary />
            public static string Pulse { get; } = ResourceManager.GetString("Pulse");

            /// <summary />
            public static string QuestionCircle { get; } = ResourceManager.GetString("QuestionCircle");

            /// <summary />
            public static string Receipt { get; } = ResourceManager.GetString("Receipt");

            /// <summary />
            public static string Record { get; } = ResourceManager.GetString("Record");

            /// <summary />
            public static string RecordStop { get; } = ResourceManager.GetString("RecordStop");

            /// <summary />
            public static string RectangleLandscape { get; } = ResourceManager.GetString("RectangleLandscape");

            /// <summary />
            public static string Recycle { get; } = ResourceManager.GetString("Recycle");

            /// <summary />
            public static string Rhombus { get; } = ResourceManager.GetString("Rhombus");

            /// <summary />
            public static string Ribbon { get; } = ResourceManager.GetString("Ribbon");

            /// <summary />
            public static string RibbonOff { get; } = ResourceManager.GetString("RibbonOff");

            /// <summary />
            public static string RoadCone { get; } = ResourceManager.GetString("RoadCone");

            /// <summary />
            public static string Ruler { get; } = ResourceManager.GetString("Ruler");

            /// <summary />
            public static string Scales { get; } = ResourceManager.GetString("Scales");

            /// <summary />
            public static string ScanDash { get; } = ResourceManager.GetString("ScanDash");

            /// <summary />
            public static string Search { get; } = ResourceManager.GetString("Search");

            /// <summary />
            public static string Send { get; } = ResourceManager.GetString("Send");

            /// <summary />
            public static string SendBeaker { get; } = ResourceManager.GetString("SendBeaker");

            /// <summary />
            public static string Settings { get; } = ResourceManager.GetString("Settings");

            /// <summary />
            public static string Shield { get; } = ResourceManager.GetString("Shield");

            /// <summary />
            public static string ShieldQuestion { get; } = ResourceManager.GetString("ShieldQuestion");

            /// <summary />
            public static string Shifts { get; } = ResourceManager.GetString("Shifts");

            /// <summary />
            public static string Showerhead { get; } = ResourceManager.GetString("Showerhead");

            /// <summary />
            public static string SkipBack10 { get; } = ResourceManager.GetString("SkipBack10");

            /// <summary />
            public static string SkipForward10 { get; } = ResourceManager.GetString("SkipForward10");

            /// <summary />
            public static string SkipForward30 { get; } = ResourceManager.GetString("SkipForward30");

            /// <summary />
            public static string SlideAdd { get; } = ResourceManager.GetString("SlideAdd");

            /// <summary />
            public static string SlideMicrophone { get; } = ResourceManager.GetString("SlideMicrophone");

            /// <summary />
            public static string SlideTextMultiple { get; } = ResourceManager.GetString("SlideTextMultiple");

            /// <summary />
            public static string SlideTextPerson { get; } = ResourceManager.GetString("SlideTextPerson");

            /// <summary />
            public static string SlideTextSparkle { get; } = ResourceManager.GetString("SlideTextSparkle");

            /// <summary />
            public static string Space3d { get; } = ResourceManager.GetString("Space3d");

            /// <summary />
            public static string Sparkle { get; } = ResourceManager.GetString("Sparkle");

            /// <summary />
            public static string SparkleCircle { get; } = ResourceManager.GetString("SparkleCircle");

            /// <summary />
            public static string Speaker0 { get; } = ResourceManager.GetString("Speaker0");

            /// <summary />
            public static string Speaker1 { get; } = ResourceManager.GetString("Speaker1");

            /// <summary />
            public static string Speaker2 { get; } = ResourceManager.GetString("Speaker2");

            /// <summary />
            public static string SplitHorizontal { get; } = ResourceManager.GetString("SplitHorizontal");

            /// <summary />
            public static string SplitVertical { get; } = ResourceManager.GetString("SplitVertical");

            /// <summary />
            public static string Square { get; } = ResourceManager.GetString("Square");

            /// <summary />
            public static string SquareArrowForward { get; } = ResourceManager.GetString("SquareArrowForward");

            /// <summary />
            public static string SquareHint { get; } = ResourceManager.GetString("SquareHint");

            /// <summary />
            public static string SquareHintSparkles { get; } = ResourceManager.GetString("SquareHintSparkles");

            /// <summary />
            public static string SquareMultiple { get; } = ResourceManager.GetString("SquareMultiple");

            /// <summary />
            public static string Stack { get; } = ResourceManager.GetString("Stack");

            /// <summary />
            public static string StarEmphasis { get; } = ResourceManager.GetString("StarEmphasis");

            /// <summary />
            public static string Stream { get; } = ResourceManager.GetString("Stream");

            /// <summary />
            public static string SubtractCircle { get; } = ResourceManager.GetString("SubtractCircle");

            /// <summary />
            public static string SwimmingPool { get; } = ResourceManager.GetString("SwimmingPool");

            /// <summary />
            public static string Table { get; } = ResourceManager.GetString("Table");

            /// <summary />
            public static string TableBottomRow { get; } = ResourceManager.GetString("TableBottomRow");

            /// <summary />
            public static string TableDefault { get; } = ResourceManager.GetString("TableDefault");

            /// <summary />
            public static string TableLock { get; } = ResourceManager.GetString("TableLock");

            /// <summary />
            public static string TableSimple { get; } = ResourceManager.GetString("TableSimple");

            /// <summary />
            public static string TableSimpleCheckmark { get; } = ResourceManager.GetString("TableSimpleCheckmark");

            /// <summary />
            public static string TableSimpleExclude { get; } = ResourceManager.GetString("TableSimpleExclude");

            /// <summary />
            public static string TableSimpleInclude { get; } = ResourceManager.GetString("TableSimpleInclude");

            /// <summary />
            public static string Tablet { get; } = ResourceManager.GetString("Tablet");

            /// <summary />
            public static string TagLock { get; } = ResourceManager.GetString("TagLock");

            /// <summary />
            public static string TagQuestionMark { get; } = ResourceManager.GetString("TagQuestionMark");

            /// <summary />
            public static string TapDouble { get; } = ResourceManager.GetString("TapDouble");

            /// <summary />
            public static string TapSingle { get; } = ResourceManager.GetString("TapSingle");

            /// <summary />
            public static string Target { get; } = ResourceManager.GetString("Target");

            /// <summary />
            public static string Temperature { get; } = ResourceManager.GetString("Temperature");

            /// <summary />
            public static string TetrisApp { get; } = ResourceManager.GetString("TetrisApp");

            /// <summary />
            public static string Text { get; } = ResourceManager.GetString("Text");

            /// <summary />
            public static string TextAbcUnderlineDouble { get; } = ResourceManager.GetString("TextAbcUnderlineDouble");

            /// <summary />
            public static string TextBulletListSquare { get; } = ResourceManager.GetString("TextBulletListSquare");

            /// <summary />
            public static string TextBulletListSquarePerson { get; } = ResourceManager.GetString("TextBulletListSquarePerson");

            /// <summary />
            public static string TextT { get; } = ResourceManager.GetString("TextT");

            /// <summary />
            public static string Timer { get; } = ResourceManager.GetString("Timer");

            /// <summary />
            public static string Triangle { get; } = ResourceManager.GetString("Triangle");

            /// <summary />
            public static string TriangleDown { get; } = ResourceManager.GetString("TriangleDown");

            /// <summary />
            public static string TriangleLeft { get; } = ResourceManager.GetString("TriangleLeft");

            /// <summary />
            public static string TriangleRight { get; } = ResourceManager.GetString("TriangleRight");

            /// <summary />
            public static string Trophy { get; } = ResourceManager.GetString("Trophy");

            /// <summary />
            public static string TrophyLock { get; } = ResourceManager.GetString("TrophyLock");

            /// <summary />
            public static string TrophyOff { get; } = ResourceManager.GetString("TrophyOff");

            /// <summary />
            public static string VehicleCar { get; } = ResourceManager.GetString("VehicleCar");

            /// <summary />
            public static string VehicleCarCollision { get; } = ResourceManager.GetString("VehicleCarCollision");

            /// <summary />
            public static string VehicleCarParking { get; } = ResourceManager.GetString("VehicleCarParking");

            /// <summary />
            public static string Video { get; } = ResourceManager.GetString("Video");

            /// <summary />
            public static string VideoBackgroundEffect { get; } = ResourceManager.GetString("VideoBackgroundEffect");

            /// <summary />
            public static string VideoBackgroundEffectHorizontal { get; } = ResourceManager.GetString("VideoBackgroundEffectHorizontal");

            /// <summary />
            public static string VideoChat { get; } = ResourceManager.GetString("VideoChat");

            /// <summary />
            public static string VideoClip { get; } = ResourceManager.GetString("VideoClip");

            /// <summary />
            public static string VideoOff { get; } = ResourceManager.GetString("VideoOff");

            /// <summary />
            public static string VideoPeople { get; } = ResourceManager.GetString("VideoPeople");

            /// <summary />
            public static string VideoPerson { get; } = ResourceManager.GetString("VideoPerson");

            /// <summary />
            public static string VideoPersonCall { get; } = ResourceManager.GetString("VideoPersonCall");

            /// <summary />
            public static string VideoPersonClock { get; } = ResourceManager.GetString("VideoPersonClock");

            /// <summary />
            public static string Voicemail { get; } = ResourceManager.GetString("Voicemail");

            /// <summary />
            public static string Wallet { get; } = ResourceManager.GetString("Wallet");

            /// <summary />
            public static string WalletCreditCard { get; } = ResourceManager.GetString("WalletCreditCard");

            /// <summary />
            public static string Washer { get; } = ResourceManager.GetString("Washer");

            /// <summary />
            public static string Water { get; } = ResourceManager.GetString("Water");

            /// <summary />
            public static string WeatherSnowflake { get; } = ResourceManager.GetString("WeatherSnowflake");

            /// <summary />
            public static string WeatherSunny { get; } = ResourceManager.GetString("WeatherSunny");

            /// <summary />
            public static string Window { get; } = ResourceManager.GetString("Window");

            /// <summary />
            public static string WindowApps { get; } = ResourceManager.GetString("WindowApps");

            /// <summary />
            public static string WindowWrench { get; } = ResourceManager.GetString("WindowWrench");

            /// <summary />
            public static string XboxController { get; } = ResourceManager.GetString("XboxController");

            /// <summary />
            public static string XboxControllerError { get; } = ResourceManager.GetString("XboxControllerError");

        }
    }
}
