<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>$(ExampleNetVersion)</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <AssemblyName>Microsoft.FluentUI.AspNetCore.Components.Tests</AssemblyName>
    <RootNamespace>Microsoft.FluentUI.AspNetCore.Components.Tests</RootNamespace>
    <NoWarn>xUnit1069;BL0016</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core\Microsoft.FluentUI.AspNetCore.Components.csproj" />
    <ProjectReference Include="..\Tools\Components.Tests.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Dependent Test Result HTML files -->
    <None Include="**\*.verified.html" />
    <None Update="**\*.verified.html">
      <ParentFile>$([System.String]::Copy('%(FileName)').Split('.')[0])</ParentFile>
      <DependentUpon>%(ParentFile).cs</DependentUpon>
    </None>

    <None Include="**\*.received.html" />
    <None Update="**\*.received.html">
      <ParentFile>$([System.String]::Copy('%(FileName)').Split('.')[0])</ParentFile>
      <DependentUpon>%(ParentFile).cs</DependentUpon>
    </None>

    <!-- Dependent Test Result RAZOR files -->
    <None Include="**\*.verified.razor.html" />
    <None Update="**\*.verified.razor.html">
      <ParentFile>$([System.String]::Copy('%(FileName)').Split('.')[0])</ParentFile>
      <DependentUpon>%(ParentFile).razor</DependentUpon>
    </None>

    <None Include="**\*.received.razor.html" />

    <Compile Remove="Verify\**" />

    <Content Remove="Verify\**" />

    <EmbeddedResource Remove="Verify\**" />

    <None Remove="Verify\**" />
    <None Update="**\*.received.razor.html">
      <ParentFile>$([System.String]::Copy('%(FileName)').Split('.')[0])</ParentFile>
      <DependentUpon>%(ParentFile).razor</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Resources\FluentLocalizer.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FluentLocalizer.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Localization\Resources\FluentLocalizer.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FluentLocalizer.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  </Project>
