// ------------------------------------------------------------------------
// This file is licensed to you under the MIT License.
// ------------------------------------------------------------------------

using Bunit;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.JSInterop;
using Xunit;

namespace Microsoft.FluentUI.AspNetCore.Components.Tests.Components.Toast;

public class ToastInstanceTests : Bunit.BunitContext
{
    public ToastInstanceTests()
    {
        JSInterop.Mode = JSRuntimeMode.Loose;
        Services.AddFluentUIComponents();
    }

    private NotificationService GetService()
        => (NotificationService)Services.GetRequiredService<INotificationService>();

    [Fact]
    public void ToastInstance_AutoGeneratedId()
    {
        // Arrange
        var service = GetService();
        var options = new ToastOptions();

        // Act
        var instance = new ToastInstance(service, options);

        // Assert
        Assert.False(string.IsNullOrEmpty(instance.Id));
        Assert.True(instance.Index > 0);
        Assert.Same(options, instance.Options);
        Assert.Equal(ToastLifecycleStatus.Unmounted, instance.LifecycleStatus);
        Assert.NotNull(instance.Result);
    }

    [Fact]
    public void ToastInstance_UsesProvidedId()
    {
        // Arrange
        var service = GetService();
        var options = new ToastOptions { Id = "my-id" };

        // Act
        var instance = new ToastInstance(service, options);

        // Assert
        Assert.Equal("my-id", instance.Id);
    }

    [Fact]
    public void ToastInstance_IncrementsIndex()
    {
        // Arrange
        var service = GetService();

        // Act
        var first = new ToastInstance(service, new ToastOptions());
        var second = new ToastInstance(service, new ToastOptions());

        // Assert
        Assert.True(second.Index > first.Index);
    }

    [Fact]
    public void ToastInstance_ComponentType_DefaultsToNull()
    {
        // Arrange
        var service = GetService();

        // Act
        INotificationInstance instance = new ToastInstance(service, new ToastOptions());

        // Assert
        Assert.Null(instance.ComponentType);
    }

    [Fact]
    public void ToastInstance_ComponentType_FromCtor()
    {
        // Arrange
        var service = GetService();

        // Act
        INotificationInstance instance = new ToastInstance(service, typeof(FluentToast), new ToastOptions());

        // Assert
        Assert.Equal(typeof(FluentToast), instance.ComponentType);
    }

    [Fact]
    public void ToastInstance_SetStatus_UpdatesLifecycleStatus()
    {
        // Arrange
        var instance = new ToastInstance(GetService(), new ToastOptions());

        // Act
        instance.SetStatus(ToastLifecycleStatus.Visible);

        // Assert
        Assert.Equal(ToastLifecycleStatus.Visible, instance.LifecycleStatus);
    }

    [Fact]
    public void ToastInstance_SetStatus_InvokesOnStatusChange()
    {
        // Arrange
        ToastEventArgs? capturedArgs = null;
        var options = new ToastOptions
        {
            OnStatusChange = args => capturedArgs = args,
        };
        var instance = new ToastInstance(GetService(), options);

        // Act
        instance.SetStatus(ToastLifecycleStatus.Visible);

        // Assert
        Assert.NotNull(capturedArgs);
        Assert.Equal(ToastLifecycleStatus.Visible, capturedArgs!.Status);
        Assert.Same(instance, capturedArgs.Instance);
    }

    [Fact]
    public void ToastInstance_SetStatus_SameStatus_DoesNotInvokeCallbackAgain()
    {
        // Arrange
        var callCount = 0;
        var options = new ToastOptions
        {
            OnStatusChange = _ => callCount++,
        };
        var instance = new ToastInstance(GetService(), options);

        // Act
        instance.SetStatus(ToastLifecycleStatus.Visible);
        instance.SetStatus(ToastLifecycleStatus.Visible);

        // Assert
        Assert.Equal(1, callCount);
    }

    [Fact]
    public async Task ToastInstance_SetStatus_Queued_CompletesResult_WhenTimingQueued()
    {
        // Arrange
        var options = new ToastOptions { ResultTiming = ToastResultTiming.Queued };
        var instance = new ToastInstance(GetService(), options);

        // Act
        instance.SetStatus(ToastLifecycleStatus.Queued);
        var result = await instance.Result;

        // Assert
        Assert.Equal(ToastCloseReason.Programmatic, result.Reason);
    }

    [Fact]
    public async Task ToastInstance_SetStatus_Visible_CompletesResult_WhenTimingVisible()
    {
        // Arrange
        var options = new ToastOptions { ResultTiming = ToastResultTiming.Visible };
        var instance = new ToastInstance(GetService(), options);

        // Act
        instance.SetStatus(ToastLifecycleStatus.Visible);
        var result = await instance.Result;

        // Assert
        Assert.Equal(ToastCloseReason.Programmatic, result.Reason);
    }

    [Fact]
    public void ToastInstance_SetStatus_Visible_DoesNotCompleteResult_WhenTimingClosed()
    {
        // Arrange
        var options = new ToastOptions { ResultTiming = ToastResultTiming.Closed };
        var instance = new ToastInstance(GetService(), options);

        // Act
        instance.SetStatus(ToastLifecycleStatus.Visible);

        // Assert
        Assert.False(instance.Result.IsCompleted);
    }

    [Fact]
    public void ToastInstance_NotificationService_ReturnsOwningService()
    {
        // Arrange
        var service = GetService();

        // Act
        var instance = new ToastInstance(service, new ToastOptions());

        // Assert
        Assert.Same(service, instance.NotificationService);
    }

    /// <summary>
    /// Subscribes a fake provider so the service considers a provider available,
    /// then shows a toast and returns its registered <see cref="ToastInstance"/>.
    /// </summary>
    private ToastInstance ShowRegisteredToast(NotificationService service, ToastOptions options)
    {
        service.Subscribe("toast-provider", _ => Task.CompletedTask);
        _ = service.ShowToastAsync(options);
        return (ToastInstance)service.GetToastInstance(options.Id!)!;
    }

    [Fact]
    public async Task ToastInstance_CloseAsync_ClosesThroughService_WithProgrammaticReason()
    {
        // Arrange
        var service = GetService();
        var instance = ShowRegisteredToast(service, new ToastOptions { Id = "close-1", Title = "Title" });

        // Act
        await instance.CloseAsync();
        var result = await instance.Result;

        // Assert
        Assert.Equal(ToastLifecycleStatus.Dismissed, instance.LifecycleStatus);
        Assert.Equal(ToastCloseReason.Programmatic, result.Reason);
        Assert.Same(instance, result.Instance);
    }

    [Fact]
    public async Task ToastInstance_CloseAsync_WithReasonAndData_PassesThemToResult()
    {
        // Arrange
        var service = GetService();
        var instance = ShowRegisteredToast(service, new ToastOptions { Id = "close-2", Title = "Title", ResultTiming = ToastResultTiming.Closed });

        // Act
        await instance.CloseAsync(ToastCloseReason.QuickAction, "payload");
        var result = await instance.Result;

        // Assert
        Assert.Equal(ToastLifecycleStatus.Dismissed, instance.LifecycleStatus);
        Assert.Equal(ToastCloseReason.QuickAction, result.Reason);
        Assert.Equal("payload", result.Data);
        Assert.Same(instance, result.Instance);
    }

    [Fact]
    public async Task ToastInstance_CloseAsync_WithReasonOnly_HasNullData()
    {
        // Arrange
        var service = GetService();
        var instance = ShowRegisteredToast(service, new ToastOptions { Id = "close-3", Title = "Title", ResultTiming = ToastResultTiming.Closed });

        // Act
        await instance.CloseAsync(ToastCloseReason.TimedOut);
        var result = await instance.Result;

        // Assert
        Assert.Equal(ToastLifecycleStatus.Dismissed, instance.LifecycleStatus);
        Assert.Equal(ToastCloseReason.TimedOut, result.Reason);
        Assert.Null(result.Data);
    }
}

