# ************************************************************
# PowerShell Script to extract all FluentUI CSS Variables
# from the web-components.d.ts file
#
# Usage:
#    1. Set the lastest `@fluentui/web-components` package version in the `package.json`.
#    2. Run `npm install` to install the latest package.
#    3. Open the PowerShell terminal in the `Core.Scripts` directory.
#    4. Run this Script using the following command: `.\_ExtractCssVariables.ps1`
#    5. The result is automatically written to the `StylesVariables.cs` file.
# ************************************************************

# Read the content of the file
$fileContent = Get-Content -Path ".\node_modules\@fluentui\web-components\dist\web-components.d.ts"

# Use a regular expression to find matches
# Group 1 & 2: Categories, Group 3: Name, Group 4: Variable value
$matches = [regex]::Matches($fileContent, 'export declare const\s+([a-z]+)([A-Z]?[a-z]+)?(\w+)?\s*=\s*"([^"]+)"')

# Dictionary to sort by Group1 and Group2
$result = @{}

# Collect output lines
$lines = [System.Collections.Generic.List[string]]::new()

foreach ($match in $matches) {
    if ($match.Groups[1].Value -ne "z") {       # Skip zIndex
        $g1 = $match.Groups[1].Value + "s"      # Pluralize the group name
        $g2 = $match.Groups[2].Value
        $g3 = $match.Groups[3].Value
        $g4 = $match.Groups[4].Value

        # Capitalize the first letter, keep the rest
        $g1 = $g1.Substring(0,1).ToUpper() + $g1.Substring(1)

        if (-not $result.ContainsKey($g1)) {
            $result[$g1] = @{}
        }

        if (-not $result[$g1].ContainsKey($g2)) {
            $result[$g1][$g2] = @()
        }

        $result[$g1][$g2] += [PSCustomObject]@{
            Groupe3 = $g3
            Groupe4 = $g4
        }
    }
}

# Fix names starting with 2X, 3X, 4X, 5X, or 6X by moving those 2 chars to the end
# e.g. 2XLarge => Large2X
function Fix-SizeName($name) {
    if ($name -match '^([1-9]X)(.+)$') {
        return $Matches[2] + $Matches[1]
    }
    return $name
}

# Display the result
$lines.Add("// ------------------------------------------------------------------------")
$lines.Add("// This file is licensed to you under the MIT License.")
$lines.Add("// ------------------------------------------------------------------------")
$lines.Add("")
$lines.Add("//------------------------------------------------------------------------------")
$lines.Add("// <auto-generated>")
$lines.Add("//     This code was generated by a tool.")
$lines.Add("//")
$lines.Add("//     Changes to this file may cause incorrect behavior and will be lost if")
$lines.Add("//     the code is regenerated.")
$lines.Add("// </auto-generated>")
$lines.Add("//------------------------------------------------------------------------------")
$lines.Add("")
$lines.Add("namespace Microsoft.FluentUI.AspNetCore.Components;")
$lines.Add("")
$lines.Add("/// <summary />")
$lines.Add("public partial class StylesVariables")
$lines.Add("{")

foreach ($g1 in $result.Keys) {
    $lines.Add("    /// <summary />")
    $lines.Add("    public partial class $g1")
    $lines.Add("    {")

    # Direct constants
    if ($g1 -eq "Durations" -or $g1 -eq "Shadows") {

        if ($g1 -eq "Shadows") {
            $prefix = $g1
        }
        else {
            $prefix = ""
        }

        foreach ($g2 in $result[$g1].Keys) {
            foreach ($entry in $result[$g1][$g2]) {
                $lines.Add("        /// <summary />")
                $lines.Add("        public const string $(Fix-SizeName("$prefix$g2$($entry.Groupe3)")) = ""$($entry.Groupe4)"";")
                $lines.Add("")
            }
        }
    }

     # Sub category: Group2
    else {
        foreach ($g2 in $result[$g1].Keys) {
            $lines.Add("        /// <summary />")
            $lines.Add("        public partial class $g2")
            $lines.Add("        {")
            foreach ($entry in $result[$g1][$g2]) {
                if ($entry.Groupe3 -eq "") {
                    $entry.Groupe3 = "Default"
                }

                $lines.Add("            /// <summary />")
                $lines.Add("            public const string $(Fix-SizeName($entry.Groupe3)) = ""$($entry.Groupe4)"";")
                $lines.Add("")
            }
            $lines.Add("        }")
        }
    }
    $lines.Add("    }")
}
$lines.Add("}")

# Write the result to the console
$lines | Write-Output

# Write the result to the StylesVariables.cs file
$outputPath = Join-Path $PSScriptRoot "..\Core\Components\Theme\Styles\StylesVariables.cs"
$lines | Set-Content -Path $outputPath -Encoding UTF8
Write-Host "Written to: $outputPath"

# Extract the matched item names
# $itemNames = foreach ($match in $matches) {
#     $name = $match.Groups[1].Value
#     $value = $match.Groups[2].Value
#     if (-not $name.StartsWith("zIndex")) {
#         # Capitalize the first letter, keep the rest
#         $capitalized  = $name.Substring(0,1).ToUpper() + $name.Substring(1)
#         "/// <summary>"
#         "/// $value"
#         "/// </summary>"
#         "public const string " + $capitalized + " = """ + $value + """;"
#         ""  # Empty line
#     }
# }
