import * as esbuild from 'esbuild'
import { glob } from 'glob'
import { writeFile, unlink } from 'fs/promises';
import pkg from './package.json' with { type: 'json' }
import fs from "fs";
import path from "path";

const rawBuildMode = process.argv.find(a => a.startsWith('--build-mode='))?.split('=')[1];
const buildMode = rawBuildMode === "Release" ? "Release" : "Debug";

const constantsFile = path.resolve("src/BuildConstants.ts");
fs.writeFileSync(constantsFile, `// This file is generated by a tool. Do not change!\nexport const BUILD_MODE = '${buildMode}';\n`);

// JS: Microsoft.FluentUI.AspNetCore.Components.lib.module.js
await esbuild.build({
    entryPoints: [pkg.source],
    bundle: true,
    minify: buildMode !== "Debug",
    sourcemap: buildMode === "Debug",
    logLevel: 'info',
    target: 'es2022',
    format: 'esm',
    outfile: pkg.main,
    legalComments: 'none',
    external: ['imask', 'sortablejs'], // Exclude imask, sortablejs from bundle - loaded via CDN
});

// CSS: Microsoft.FluentUI.AspNetCore.Components.bundle.scp.css
const allStyleFile = 'all-styles.css';
const files = await glob(pkg.cssFiles);
const content = files.map(file => `@import "${file.replace(/\\/g, '/')}";`).join('\n');

await writeFile(allStyleFile, content);
await esbuild.build({
    entryPoints: [allStyleFile],
    loader: { '.css': 'css' },
    outfile: pkg.cssBundle,
    bundle: true,
    minify: true,
    sourcemap: false,
});
await unlink(allStyleFile);
