// ------------------------------------------------------------------------
// This file is licensed to you under the MIT License.
// ------------------------------------------------------------------------

using Bunit;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.JSInterop;
using Xunit;

namespace Microsoft.FluentUI.AspNetCore.Components.Tests.Components.MessageBar;

public class MessageBarInstanceTests : Bunit.BunitContext
{
    public MessageBarInstanceTests()
    {
        JSInterop.Mode = JSRuntimeMode.Loose;
        Services.AddFluentUIComponents();
    }

    [Fact]
    public void MessageBarInstance_AutoGeneratedId()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();
        var options = new MessageBarOptions { Section = "section" };

        // Act
        var instance = new MessageBarInstance(service, options);

        // Assert
        Assert.False(string.IsNullOrEmpty(instance.Id));
        Assert.True(instance.Index > 0);
        Assert.Equal(MessageBarLifecycleStatus.Visible, instance.LifecycleStatus);
        Assert.Same(options, instance.Options);
        Assert.NotNull(instance.Result);
    }

    [Fact]
    public void MessageBarInstance_UsesProvidedId()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();
        var options = new MessageBarOptions { Section = "section", Id = "fixed-id" };

        // Act
        var instance = new MessageBarInstance(service, options);

        // Assert
        Assert.Equal("fixed-id", instance.Id);
    }

    [Fact]
    public void MessageBarInstance_IncrementsIndex()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();

        // Act
        var first = new MessageBarInstance(service, new MessageBarOptions { Section = "s" });
        var second = new MessageBarInstance(service, new MessageBarOptions { Section = "s" });

        // Assert
        Assert.True(second.Index > first.Index);
    }

    [Fact]
    public void MessageBarInstance_ComponentType_DefaultsToNull()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();

        // Act
        IMessageBarInstance instance = new MessageBarInstance(service, new MessageBarOptions { Section = "s" });

        // Assert
        Assert.Null(instance.ComponentType);
    }

    [Fact]
    public void MessageBarInstance_ComponentType_FromCtor()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();

        // Act
        IMessageBarInstance instance = new MessageBarInstance(service, typeof(FluentMessageBar), new MessageBarOptions { Section = "s" });

        // Assert
        Assert.Equal(typeof(FluentMessageBar), instance.ComponentType);
    }

    [Fact]
    public async Task MessageBarInstance_CloseAsync_NoResult_CallsService()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();
        var options = new MessageBarOptions { Section = "section", Id = "to-close" };
        var instance = new MessageBarInstance(service, options);
        ((IFluentServiceBase<IMessageBarInstance>)service).Items.TryAdd(instance.Id, instance);
        ((IFluentServiceBase<IMessageBarInstance>)service).ProviderId = "provider";

        // Act
        await instance.CloseAsync();

        // Assert
        Assert.Equal(MessageBarLifecycleStatus.Unmounted, instance.LifecycleStatus);

        var result = await instance.Result;
        Assert.Equal(MessageBarCloseReason.Programmatic, result.Reason);
    }

    [Fact]
    public async Task MessageBarInstance_CloseAsync_WithResult_PassesReason()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();
        var options = new MessageBarOptions { Section = "section" };
        var instance = new MessageBarInstance(service, options);
        ((IFluentServiceBase<IMessageBarInstance>)service).Items.TryAdd(instance.Id, instance);
        ((IFluentServiceBase<IMessageBarInstance>)service).ProviderId = "provider";

        // Act
        await instance.CloseAsync(MessageBarResult.OfDismissed("payload"));

        // Assert
        var result = await instance.Result;
        Assert.Equal(MessageBarCloseReason.Dismissed, result.Reason);
        Assert.Equal("payload", result.Data);
    }

    [Fact]
    public void MessageBarInstance_Dispose_DisposesLifetimeCts()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();
        var instance = new MessageBarInstance(service, new MessageBarOptions { Section = "section" });

        // Act
        instance.Dispose();

        // Assert: accessing the token throws because the underlying CTS is disposed.
        Assert.Throws<ObjectDisposedException>(() => _ = instance.LifetimeCancellationToken);
    }

    [Fact]
    public void MessageBarInstance_Dispose_Twice_DoesNotThrow()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();
        var instance = new MessageBarInstance(service, new MessageBarOptions { Section = "section" });

        // Act
        instance.Dispose();

        // Assert
        var exception = Record.Exception(() => instance.Dispose());
        Assert.Null(exception);
    }

    [Fact]
    public void MessageBarInstance_CancelLifetime_AfterDispose_DoesNotThrow()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();
        var instance = new MessageBarInstance(service, new MessageBarOptions { Section = "section" });
        instance.Dispose();

        // Act & Assert
        var exception = Record.Exception(() => instance.CancelLifetime());
        Assert.Null(exception);
    }

    [Fact]
    public void MessageBarInstance_CancelLifetime_Twice_DoesNotThrow()
    {
        // Arrange
        var service = (NotificationService)Services.GetRequiredService<INotificationService>();
        var instance = new MessageBarInstance(service, new MessageBarOptions { Section = "section" });

        // Act
        instance.CancelLifetime();
        var token = instance.LifetimeCancellationToken;

        // Assert
        var exception = Record.Exception(() => instance.CancelLifetime());
        Assert.Null(exception);
        Assert.True(token.IsCancellationRequested);
    }
}
