//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentUI.Demo.Client.Samples.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Faces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Faces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentUI.Demo.Client.Samples.Data.Faces", typeof(Faces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEBKwErAAD/4QCSRXhpZgAATU0AKgAAAAgABQEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAAExAAIAAAAQAAAAWodpAAQAAAABAAAAagAAAAAAAAErAAAAAQAAASsAAAABcGFpbnQubmV0IDUuMC45AAACoAIABAAAAAEAAAPooAMABAAAAAEAAALjAAAAAAAA/+EIHWh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkltYWdlOjpFeGlmVG9vbCAxMi41NiI+DQogIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3lu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Face1 {
            get {
                return ResourceManager.GetString("Face1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEBKwErAAD/4QCSRXhpZgAATU0AKgAAAAgABQEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAAExAAIAAAAQAAAAWodpAAQAAAABAAAAagAAAAAAAAErAAAAAQAAASsAAAABcGFpbnQubmV0IDUuMC45AAACoAIABAAAAAEAAAPooAMABAAAAAEAAAKbAAAAAAAA/+EHq2h0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkltYWdlOjpFeGlmVG9vbCAxMi41NiI+DQogIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3lu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Face2 {
            get {
                return ResourceManager.GetString("Face2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEBKwErAAD/4QCSRXhpZgAATU0AKgAAAAgABQEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAAExAAIAAAAQAAAAWodpAAQAAAABAAAAagAAAAAAAAErAAAAAQAAASsAAAABcGFpbnQubmV0IDUuMC45AAACoAIABAAAAAEAAAPooAMABAAAAAEAAAJ9AAAAAAAA/+EIn2h0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkltYWdlOjpFeGlmVG9vbCAxMi41NiI+DQogIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3lu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Face3 {
            get {
                return ResourceManager.GetString("Face3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEBKwErAAD/4QCSRXhpZgAATU0AKgAAAAgABQEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAAExAAIAAAAQAAAAWodpAAQAAAABAAAAagAAAAAAAAErAAAAAQAAASsAAAABcGFpbnQubmV0IDUuMC45AAACoAIABAAAAAEAAAPooAMABAAAAAEAAAIPAAAAAAAA/+EILmh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkltYWdlOjpFeGlmVG9vbCAxMi41NiI+DQogIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3lu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Face4 {
            get {
                return ResourceManager.GetString("Face4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEBLAEsAAD/4QBmRXhpZgAATU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAAExAAIAAAAQAAAATgAAAAAAAAEsAAAAAQAAASwAAAABcGFpbnQubmV0IDUuMC45AP/hCAlodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+DQo8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJJbWFnZTo6RXhpZlRvb2wgMTIuNTYiPg0KICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPg0KICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Face5 {
            get {
                return ResourceManager.GetString("Face5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEBKwErAAD/4QCSRXhpZgAATU0AKgAAAAgABQEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAAExAAIAAAAQAAAAWodpAAQAAAABAAAAagAAAAAAAAErAAAAAQAAASsAAAABcGFpbnQubmV0IDUuMC45AAACoAIABAAAAAEAAAPooAMABAAAAAEAAAKbAAAAAAAA/+EIIWh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkltYWdlOjpFeGlmVG9vbCAxMi41NiI+DQogIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3lu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Face6 {
            get {
                return ResourceManager.GetString("Face6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEBKwErAAD/4QCSRXhpZgAATU0AKgAAAAgABQEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAAExAAIAAAAQAAAAWodpAAQAAAABAAAAagAAAAAAAAErAAAAAQAAASsAAAABcGFpbnQubmV0IDUuMC45AAACoAIABAAAAAEAAAPooAMABAAAAAEAAAKbAAAAAAAA/+EIOmh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkltYWdlOjpFeGlmVG9vbCAxMi41NiI+DQogIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3lu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Face7 {
            get {
                return ResourceManager.GetString("Face7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4AAQSkZJRgABAQEBKwErAAD/4QCSRXhpZgAATU0AKgAAAAgABQEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAAExAAIAAAAQAAAAWodpAAQAAAABAAAAagAAAAAAAAErAAAAAQAAASsAAAABcGFpbnQubmV0IDUuMC45AAACoAIABAAAAAEAAAPooAMABAAAAAEAAALuAAAAAAAA/+EIIGh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4NCjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkltYWdlOjpFeGlmVG9vbCAxMi41NiI+DQogIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3lu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Face8 {
            get {
                return ResourceManager.GetString("Face8", resourceCulture);
            }
        }
    }
}
