//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentUI.Demo.Client.Samples.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoremIpsum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoremIpsum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentUI.Demo.Client.Samples.Data.LoremIpsum", typeof(LoremIpsum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum odor amet, consectetuer adipiscing elit. Dolor ultrices neque phasellus praesent maecenas, vestibulum turpis ridiculus. Odio habitasse nunc placerat sociosqu urna; auctor sed tortor. Dignissim vivamus tempus accumsan penatibus elementum convallis? Euismod duis quam enim suscipit mollis et. Mauris ac conubia libero rhoncus dui hac a? Quam ut felis dui, magna mattis vulputate turpis. Ullamcorper torquent non turpis est laoreet quisque aliquam bibendum..
        /// </summary>
        internal static string Lorem1 {
            get {
                return ResourceManager.GetString("Lorem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilisi aptent nibh sodales amet nisl. Praesent phasellus non eros cursus metus maximus id montes nostra. Fusce mauris vitae nisl erat porttitor vivamus vivamus libero. Vehicula hac sodales sociosqu class finibus phasellus. Metus nostra nullam porttitor tellus curae ut. Finibus aenean varius risus pellentesque venenatis auctor risus fames. Quis pulvinar sit parturient nibh; vulputate magna fusce senectus..
        /// </summary>
        internal static string Lorem10 {
            get {
                return ResourceManager.GetString("Lorem10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netus feugiat cursus proin maximus maecenas semper vulputate luctus. Faucibus pulvinar dapibus potenti rhoncus, eros eros risus hac molestie. In habitasse convallis eget habitasse magna tempus; vestibulum proin. Adipiscing sollicitudin diam cursus maximus nec elementum consectetur sociosqu. Ullamcorper nisl auctor bibendum dis; fermentum porta class quisque. Auctor primis integer efficitur ligula sociosqu volutpat blandit. Facilisi et litora aenean dignissim lobortis semper varius. Lacinia sit gravida erat  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lorem2 {
            get {
                return ResourceManager.GetString("Lorem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fringilla bibendum magnis velit inceptos arcu; suspendisse tempor conubia. Molestie augue fames dis diam blandit efficitur congue sem arcu. Litora pharetra vitae finibus orci sodales tristique taciti at magnis. Aptent quam aptent aliquam semper cubilia dis praesent. Orci commodo nunc faucibus sollicitudin hac amet. Curabitur tortor massa maecenas potenti ante rutrum fermentum. Magna eget primis sagittis tellus eget aenean maximus..
        /// </summary>
        internal static string Lorem3 {
            get {
                return ResourceManager.GetString("Lorem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id vel hendrerit arcu, suscipit iaculis natoque finibus consectetur. Ridiculus netus lacinia ultrices adipiscing blandit nunc faucibus litora facilisis. Praesent libero senectus cras integer dignissim. Donec elit sit vulputate nascetur venenatis vestibulum magna ultrices dis. Mollis primis vulputate sit, risus felis metus taciti non. Mauris fringilla velit fusce fermentum finibus aptent faucibus himenaeos finibus. Proin diam elementum scelerisque commodo volutpat et dictum consectetur..
        /// </summary>
        internal static string Lorem4 {
            get {
                return ResourceManager.GetString("Lorem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finibus ligula lectus; enim nunc primis amet. Eget hendrerit habitasse turpis est maecenas urna gravida urna. Purus libero enim potenti vitae curae erat. Facilisi ad at mus lacus mi. Dictum dapibus metus pharetra nulla duis pharetra. Primis elit libero tortor blandit dui, eros quisque sollicitudin. Neque augue lacus dapibus tempus conubia commodo proin. Laoreet auctor turpis phasellus id parturient volutpat..
        /// </summary>
        internal static string Lorem5 {
            get {
                return ResourceManager.GetString("Lorem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mattis dapibus vestibulum fames condimentum ornare vel nascetur eleifend inceptos. Nec phasellus massa turpis a consequat gravida varius dignissim vehicula. Dui commodo elementum mollis, proin sed erat. Sollicitudin viverra penatibus vehicula suscipit, consequat dapibus nec a vitae. Nam ante at nascetur habitant, sapien facilisis dapibus. Praesent leo aliquet nisi taciti ligula. Habitasse auctor aliquam sodales cursus fermentum ultrices inceptos..
        /// </summary>
        internal static string Lorem6 {
            get {
                return ResourceManager.GetString("Lorem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potenti eu pellentesque habitasse duis purus egestas mattis lacus. Euismod mus facilisi ante lectus quis ultrices malesuada. Nibh feugiat amet adipiscing justo tincidunt quam inceptos velit habitasse. Magna fusce dignissim ultrices lectus himenaeos ut sapien. Curabitur eleifend conubia elit; magna lobortis metus. Quis cras lobortis integer tellus maximus. Metus est tellus class magnis fermentum massa id..
        /// </summary>
        internal static string Lorem7 {
            get {
                return ResourceManager.GetString("Lorem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcu convallis sed fermentum scelerisque consequat. Gravida justo nulla cubilia magna quam maecenas rutrum sed. Felis lacus aenean leo in vel maximus neque nibh. Elementum faucibus mi gravida congue dis est. Litora elit adipiscing phasellus luctus nulla habitasse primis potenti. Nec ultricies lectus senectus amet nostra at tincidunt. Etiam ultricies vulputate velit nisi ultricies inceptos. Lacinia mi lacus sem, non aliquam id. Facilisis arcu vitae aenean accumsan hendrerit ultrices fringilla nostra taciti.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lorem8 {
            get {
                return ResourceManager.GetString("Lorem8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feugiat placerat interdum arcu nec nisi hac vestibulum vitae. Rutrum curabitur senectus proin curabitur interdum. Pulvinar semper volutpat vel odio penatibus; congue accumsan? Curabitur etiam potenti consequat mattis consectetur. Turpis inceptos porttitor donec dolor maximus ornare integer mus. Hendrerit metus eros sem felis arcu..
        /// </summary>
        internal static string Lorem9 {
            get {
                return ResourceManager.GetString("Lorem9", resourceCulture);
            }
        }
    }
}
