# Build and test Core project.

pr:
- main
- dev
trigger:
- main
- dev

# Build.BuildNumber (see versioning.yml)
name: $(FileVersion).$(Year:yy)$(DayOfYear).$(Rev:r)

# pool:
#   vmImage: 'windows-2022'
pool:
  name: HostedDVO
  demands:
   - agent.name -equals Hosted-FluentUI
   
extends:
  template: common/template-to-build-projects.yml
  parameters:
      Projects: |
       **/Microsoft.FluentUI.AspNetCore.Components.csproj
      Tests: |
       **/Microsoft.FluentUI.AspNetCore.Components.Tests.csproj
