# Build Demo project.

pr: none      # Disable pull request triggers.
trigger:
- main
- dev

# Build.BuildNumber (see versioning.yml)
name: $(FileVersion).$(Year:yy)$(DayOfYear).$(Rev:r)

pool:
  name: Fluent-Blazor-1ESPT

extends:
  template: common/template-to-build-projects.yml
  parameters:
      Projects: |
       **/FluentUI.Demo.Client.csproj
      IsDemo: true
