# Build the Demo projects.

pr: none      # Disable pull request triggers.
trigger: none # Disable push triggers.

# Build.BuildNumber
# use the variable "PublicVersion" to define a public version number (Ex. 2.3.6 or 3.0.0-preview.3)
name: $(VersionMajor).$(Year:yy)$(DayOfYear).$(Rev:r)

pool:
  vmImage: 'windows-2022'

extends:
  template: common/template-to-build-projects.yml
  parameters:
      Projects: |
       **/FluentUI.Demo.Client.csproj
      Demos: |
       **/FluentUI.Demo.Client.csproj
