# Build and test projects.

pr:
- main
- dev
trigger:
- main
- dev

# Build.BuildNumber (see versioning.yml)
name: $(FileVersion).$(Year:yy)$(DayOfYear).$(Rev:r)

pool:
  vmImage: 'windows-2022'

extends:
  template: common/template-to-build-projects.yml
  parameters:
      Projects: |
       **/Microsoft.Fast.Components.FluentUI.csproj
      Tests: |
       **/Microsoft.Fast.Components.FluentUI.Tests.csproj
