# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pr: none # Disable pull request triggers.
trigger:
- users/dvoituron/icons

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # Build Icons Lib only (build time too long for Emojis Lib on Azure DevOps)
  projects: |
   **/Microsoft.Fast.Components.FluentUI.Icons.csproj

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet tools

- task: UseDotNet@2
  displayName: 'Install .NET 6.0'
  inputs:
    version: 6.0.408
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: 'Install .NET 7.0'
  inputs:
    version: 7.0.203
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: 'Install .NET 8.0'
  inputs:
    version: 8.0.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Install dependencies
  inputs:
    command: 'restore'
    projects: $(projects)

- task: DotNetCoreCLI@2
  displayName: "Build Libs"
  inputs:
    command: 'build'
    projects: '$(projects)'
    arguments: '-c $(buildConfiguration)'