# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- users/dvoituron/icons

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projects: |
   **/Microsoft.Fast.Components.FluentUI.Icons.csproj
   **/Microsoft.Fast.Components.FluentUI.Emojis.csproj

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet tools

- task: UseDotNet@2
  displayName: 'Install .NET 7.0'
  inputs:
    version: 7.0.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Install dependencies
  inputs:
    command: 'restore'
    projects: $(projects)

- task: DotNetCoreCLI@2
  displayName: "Build Icons and Emojis"
  inputs:
    command: 'build'
    projects: '$(projects)'
    arguments: '-c $(buildConfiguration-'