# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pr: none # Disable pull request triggers.
trigger:
- users/dvoituron/pipeline/version

variables:
  ${{ if eq(variables['PackageVersion'], '') }}:
    VersionAssembly: $(VersionMajor).$(Year:yy)$(DayOfYear).$(Rev:r)
  ${{ else }}:
    VersionAssembly: $(PackageVersion)

# Build.BuildNumber
name: $(VersionAssembly)

pool:
  vmImage: 'windows-2022'

extends:
  template: common/template-to-build-projects.yml
  parameters:
      Projects: |
       **/Microsoft.Fast.Components.FluentUI.Icons.csproj
