# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- users/dvoituron/icons

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/FluentUI.Icons.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: "Install .NET8 SDK"
  inputs:
    packageType: 'sdk'
    version: '8.0.100-preview.5.23303.2'
    includePreviewVersions: true

- task: NuGetCommand@2
  displayName: "Restore NuGets"
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: "Build Icons and Emojis"
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c Release'