# Build and test projects.
pr: none      # Disable pull request triggers.
trigger: none # Disable push triggers.

# Build.BuildNumber (see versioning.yml)
name: $(FileVersion).$(Year:yy)$(DayOfYear).$(Rev:r)

# TODO: To REMOVE - INCLUDE IN ICONS.YML

# pool:
#   name: HostedDVO
#   demands:
#    - agent.name -equals Hosted-FluentUI 

# extends:
#   template: common/template-to-build-projects.yml
#   parameters:
#       Projects: |
#        **/Microsoft.Fast.Components.FluentUI.Emojis.csproj