# Build Demo Project.

pr: none      # Disable pull request triggers.
trigger: none # Disable push triggers.

# Build.BuildNumber
# use the variable "PublicVersion" to define a public version number (Ex. 2.3.6 or 3.0.0-preview.3)
name: $(VersionMajor).$(Year:yy)$(DayOfYear).$(Rev:r)

pool:
  vmImage: 'windows-2022'

parameters:
  - name: Projects
    value: |
       **/FluentUI.Demo.Client.csproj.csproj

<<: common/template-to-build-projects.yml

steps:

  # Publish the project
  - task: DotNetCoreCLI@2
    displayName: 'Publish $(Build.BuildNumber)'
    inputs:
      command: 'publish'
      projects: ${{ parameters.Projects }}
      arguments: '--configuration Release --output $(Build.SourcesDirectory)\Publish'