# Build Demo project.

pr: none      # Disable pull request triggers.
trigger:
- main
- dev

# Build.BuildNumber (see versioning.yml)
name: $(FileVersion).$(Year:yy)$(DayOfYear).$(Rev:r)

pool:
  vmImage: 'windows-2022'

variables:
- group: Versioning # These variables are in Azure DevOps / Pipelines / Library

- name: Projects
  value: |
      **/FluentUI.Demo.Client.csproj

steps:

  # Publish the projects
  - task: DotNetCoreCLI@2
    displayName: 'Publish $(Build.BuildNumber)'
    inputs:
      command: 'publish'
      publishWebProjects: false  # True to build all Web Projects
      projects: $(Projects)
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
      workingDirectory: '$(Build.SourcesDirectory)'
  
  # Publish the Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
