name: Publish Microsoft Fast-Blazor

pr: none
trigger: none

pool:
  vmImage: 'windows-2022'

variables:
  project: '**/Microsoft.Fast.Components.FluentUI.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet tools

- task: UseDotNet@2
  displayName: 'Install .NET 6.0'
  inputs:
    version: 6.0.407
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: 'Install .NET 7.0'
  inputs:
    version: 7.0.202
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: 'restore'
    projects: $(project)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: $(project)
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: $(project)
    versioningScheme: 'off'
    nobuild: true
    verbosityPack: 'Normal'
    feedsToUse: 'config'
    nugetConfigPath: 

- task: EsrpCodeSigning@2
  displayName: Code Signing Assemblies (Authenticode Signing)
  inputs:
    ConnectedServiceName: 'FAST-NuGet-Publishing-SC'
    FolderPath: '$(Build.ArtifactStagingDirectory)'
    Pattern: | 
      **/*.nupkg
    UseMinimatch: true
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetSign",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        },
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '200'
    MaxRetryAttempts: '5'

- task: NuGetCommand@2
  displayName: Publish to NuGet
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)\*.nupkg;'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NugetServiceConnect'
