name: Microsoft Fast-Blazor Publish

pr: none
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  project: 'src\Microsoft.Fast.Components.FluentUI\Microsoft.Fast.Components.FluentUI.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet tools

- task: NuGetCommand@2
  displayName: Install dependencies
  inputs:
    restoreSolution: '$(project)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'dotnet nuget push $[(Build.ArtifactStagingDirectory)\(ls -t *.nupkg)] --api-key GITHUB_PAT --source "github"'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    nugetConfigPath: $(project)

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/Microsoft.Fast.Components.FluentUI.csproj'
    versioningScheme: 'off'

- task: EsrpCodeSigning@1
  displayName: Code Signing Assemblies (Authenticode Signing)
  inputs:
    ConnectedServiceName: 'FAST-NuGet-Publishing-SC'
    FolderPath: '$(Build.ArtifactStagingDirectory)'
    Pattern: | 
      **/*.nupkg
    UseMinimatch: true
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetSign",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        },
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '200'
    MaxRetryAttempts: '5'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'custom'
#     custom: 'dotnet nuget push '$[(Build.ArtifactStagingDirectory)\(ls -t *.nupkg)]' --api-key GITHUB_PAT --source "github"'

# - task: NuGetCommand@2
#   displayName: Publish to GitHub
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)\*.nupkg;'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'GitHubServiceConnect'

# - task: NuGetCommand@2
#   displayName: Publish to NuGet
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)\*.nupkg;'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'NugetServiceConnect'