
# Build and test projects.
pr: none      # Disable pull request triggers.
trigger: none # Disable push triggers.

# Build.BuildNumber
# use the variable "PublicVersion" to define a public version number (Ex. 2.3.6 or 3.0.0-preview.3)
name: $(VersionMajor).$(Year:yy)$(DayOfYear).$(Rev:r)

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: Projects		# List of projects to build
  type: string
  default: |
    **/Microsoft.Fast.Components.FluentUI.Emojis.csproj

variables:
- group: Versioning # These variables are in Azure DevOps / Pipelines / Library

steps:

  # In the main YAML script, set the "name: $(VersionMajor).$(Year:yy)$(DayOfYear).$(Rev:r)"
  - powershell: |
      $builds = "$(Build.BuildNumber)".Split('.')
      $preview = "$(VersionPreview)"
      $package = "$($builds[0]).$($builds[1]).0-preview.$($preview).$($builds[2]).$($builds[3])"
      $sign = "true";

      
      # Set the output variable for use in other tasks.
      Write-Host "##vso[task.setvariable variable=VersionPackage]${package}"
      Write-Host "##vso[task.setvariable variable=ShouldSign]${sign}"
    displayName: Compute VersionPackage

  - script: |
      echo "VersionPackage = $(VersionPackage)"
      echo "BuildNumber    = $(Build.BuildNumber)"
    displayName: Display computed variables
 
  # Since NuGet packages are generated during the build, we need to copy them to the artifacts folder.
  - task: CopyFiles@2
    displayName: 'Pack $(Build.BuildNumber)'
    inputs:
      SourceFolder: '/home/vsts/work/1/s/'
      Contents: '**/Microsoft.Fast.Components.FluentUI.Emojis.3.0.0-preview.5.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      OverWrite: true
      flattenFolders: true

  - task: EsrpCodeSigning@3
    inputs:
      ConnectedServiceName: 'ESRP Code Signing SC'
      FolderPath: '$(Build.ArtifactStagingDirectory)'
      Pattern: '**/*.nupkg'
      UseMinimatch: true
      signConfigType: 'inlineSignParams'
      inlineOperation: |
        [
                {
                    "KeyCode" : "CP-401405",
                    "OperationCode" : "NuGetSign",
                    "Parameters" : {},
                    "ToolName" : "sign",
                    "ToolVersion" : "1.0"
                },
                {
                    "KeyCode" : "CP-401405",
                    "OperationCode" : "NuGetVerify",
                    "Parameters" : {},
                    "ToolName" : "sign",
                    "ToolVersion" : "1.0"
                }
              ]
      SessionTimeout: '60'
      MaxConcurrency: '200'
      MaxRetryAttempts: '5'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
