// ------------------------------------------------------------------------
// MIT License - Copyright (c) Microsoft Corporation. All rights reserved.
// ------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.FluentUI.AspNetCore.Components;

/// <summary />
public partial class StylesVariables
{
    /// <summary />
    public partial class Curves
    {
        /// <summary />
        public partial class Decelerate
        {
            /// <summary />
            public const string Max = "var(--curveDecelerateMax)";

            /// <summary />
            public const string Mid = "var(--curveDecelerateMid)";

            /// <summary />
            public const string Min = "var(--curveDecelerateMin)";

        }
        /// <summary />
        public partial class Linear
        {
            /// <summary />
            public const string Default = "var(--curveLinear)";

        }
        /// <summary />
        public partial class Accelerate
        {
            /// <summary />
            public const string Max = "var(--curveAccelerateMax)";

            /// <summary />
            public const string Mid = "var(--curveAccelerateMid)";

            /// <summary />
            public const string Min = "var(--curveAccelerateMin)";

        }
        /// <summary />
        public partial class Easy
        {
            /// <summary />
            public const string Ease = "var(--curveEasyEase)";

            /// <summary />
            public const string EaseMax = "var(--curveEasyEaseMax)";

        }
    }
    /// <summary />
    public partial class Shadows
    {
        /// <summary />
        public const string Shadows16 = "var(--shadow16)";

        /// <summary />
        public const string Shadows16Brand = "var(--shadow16Brand)";

        /// <summary />
        public const string Shadows2 = "var(--shadow2)";

        /// <summary />
        public const string Shadows28 = "var(--shadow28)";

        /// <summary />
        public const string Shadows28Brand = "var(--shadow28Brand)";

        /// <summary />
        public const string Shadows2Brand = "var(--shadow2Brand)";

        /// <summary />
        public const string Shadows4 = "var(--shadow4)";

        /// <summary />
        public const string Shadows4Brand = "var(--shadow4Brand)";

        /// <summary />
        public const string Shadows64 = "var(--shadow64)";

        /// <summary />
        public const string Shadows64Brand = "var(--shadow64Brand)";

        /// <summary />
        public const string Shadows8 = "var(--shadow8)";

        /// <summary />
        public const string Shadows8Brand = "var(--shadow8Brand)";

    }
    /// <summary />
    public partial class Durations
    {
        /// <summary />
        public const string Slower = "var(--durationSlower)";

        /// <summary />
        public const string Gentle = "var(--durationGentle)";

        /// <summary />
        public const string Fast = "var(--durationFast)";

        /// <summary />
        public const string Slow = "var(--durationSlow)";

        /// <summary />
        public const string UltraFast = "var(--durationUltraFast)";

        /// <summary />
        public const string UltraSlow = "var(--durationUltraSlow)";

        /// <summary />
        public const string Normal = "var(--durationNormal)";

        /// <summary />
        public const string Faster = "var(--durationFaster)";

    }
    /// <summary />
    public partial class Borders
    {
        /// <summary />
        public partial class Radius
        {
            /// <summary />
            public const string Circular = "var(--borderRadiusCircular)";

            /// <summary />
            public const string Large = "var(--borderRadiusLarge)";

            /// <summary />
            public const string Medium = "var(--borderRadiusMedium)";

            /// <summary />
            public const string None = "var(--borderRadiusNone)";

            /// <summary />
            public const string Small = "var(--borderRadiusSmall)";

            /// <summary />
            public const string XLarge = "var(--borderRadiusXLarge)";

        }
    }
    /// <summary />
    public partial class Fonts
    {
        /// <summary />
        public partial class Weight
        {
            /// <summary />
            public const string Bold = "var(--fontWeightBold)";

            /// <summary />
            public const string Medium = "var(--fontWeightMedium)";

            /// <summary />
            public const string Regular = "var(--fontWeightRegular)";

            /// <summary />
            public const string Semibold = "var(--fontWeightSemibold)";

        }
        /// <summary />
        public partial class Family
        {
            /// <summary />
            public const string Base = "var(--fontFamilyBase)";

            /// <summary />
            public const string Monospace = "var(--fontFamilyMonospace)";

            /// <summary />
            public const string Numeric = "var(--fontFamilyNumeric)";

        }
        /// <summary />
        public partial class Size
        {
            /// <summary />
            public const string Base100 = "var(--fontSizeBase100)";

            /// <summary />
            public const string Base200 = "var(--fontSizeBase200)";

            /// <summary />
            public const string Base300 = "var(--fontSizeBase300)";

            /// <summary />
            public const string Base400 = "var(--fontSizeBase400)";

            /// <summary />
            public const string Base500 = "var(--fontSizeBase500)";

            /// <summary />
            public const string Base600 = "var(--fontSizeBase600)";

            /// <summary />
            public const string Hero1000 = "var(--fontSizeHero1000)";

            /// <summary />
            public const string Hero700 = "var(--fontSizeHero700)";

            /// <summary />
            public const string Hero800 = "var(--fontSizeHero800)";

            /// <summary />
            public const string Hero900 = "var(--fontSizeHero900)";

        }
    }
    /// <summary />
    public partial class Strokes
    {
        /// <summary />
        public partial class Width
        {
            /// <summary />
            public const string Thick = "var(--strokeWidthThick)";

            /// <summary />
            public const string Thicker = "var(--strokeWidthThicker)";

            /// <summary />
            public const string Thickest = "var(--strokeWidthThickest)";

            /// <summary />
            public const string Thin = "var(--strokeWidthThin)";

        }
    }
    /// <summary />
    public partial class Colors
    {
        /// <summary />
        public partial class Subtle
        {
            /// <summary />
            public const string Background = "var(--colorSubtleBackground)";

            /// <summary />
            public const string BackgroundHover = "var(--colorSubtleBackgroundHover)";

            /// <summary />
            public const string BackgroundInverted = "var(--colorSubtleBackgroundInverted)";

            /// <summary />
            public const string BackgroundInvertedHover = "var(--colorSubtleBackgroundInvertedHover)";

            /// <summary />
            public const string BackgroundInvertedPressed = "var(--colorSubtleBackgroundInvertedPressed)";

            /// <summary />
            public const string BackgroundInvertedSelected = "var(--colorSubtleBackgroundInvertedSelected)";

            /// <summary />
            public const string BackgroundLightAlphaHover = "var(--colorSubtleBackgroundLightAlphaHover)";

            /// <summary />
            public const string BackgroundLightAlphaPressed = "var(--colorSubtleBackgroundLightAlphaPressed)";

            /// <summary />
            public const string BackgroundLightAlphaSelected = "var(--colorSubtleBackgroundLightAlphaSelected)";

            /// <summary />
            public const string BackgroundPressed = "var(--colorSubtleBackgroundPressed)";

            /// <summary />
            public const string BackgroundSelected = "var(--colorSubtleBackgroundSelected)";

        }
        /// <summary />
        public partial class Palette
        {
            /// <summary />
            public const string AnchorBackground2 = "var(--colorPaletteAnchorBackground2)";

            /// <summary />
            public const string AnchorBorderActive = "var(--colorPaletteAnchorBorderActive)";

            /// <summary />
            public const string AnchorForeground2 = "var(--colorPaletteAnchorForeground2)";

            /// <summary />
            public const string BeigeBackground2 = "var(--colorPaletteBeigeBackground2)";

            /// <summary />
            public const string BeigeBorderActive = "var(--colorPaletteBeigeBorderActive)";

            /// <summary />
            public const string BeigeForeground2 = "var(--colorPaletteBeigeForeground2)";

            /// <summary />
            public const string BerryBackground1 = "var(--colorPaletteBerryBackground1)";

            /// <summary />
            public const string BerryBackground2 = "var(--colorPaletteBerryBackground2)";

            /// <summary />
            public const string BerryBackground3 = "var(--colorPaletteBerryBackground3)";

            /// <summary />
            public const string BerryBorder1 = "var(--colorPaletteBerryBorder1)";

            /// <summary />
            public const string BerryBorder2 = "var(--colorPaletteBerryBorder2)";

            /// <summary />
            public const string BerryBorderActive = "var(--colorPaletteBerryBorderActive)";

            /// <summary />
            public const string BerryForeground1 = "var(--colorPaletteBerryForeground1)";

            /// <summary />
            public const string BerryForeground2 = "var(--colorPaletteBerryForeground2)";

            /// <summary />
            public const string BerryForeground3 = "var(--colorPaletteBerryForeground3)";

            /// <summary />
            public const string BlueBackground2 = "var(--colorPaletteBlueBackground2)";

            /// <summary />
            public const string BlueBorderActive = "var(--colorPaletteBlueBorderActive)";

            /// <summary />
            public const string BlueForeground2 = "var(--colorPaletteBlueForeground2)";

            /// <summary />
            public const string BrassBackground2 = "var(--colorPaletteBrassBackground2)";

            /// <summary />
            public const string BrassBorderActive = "var(--colorPaletteBrassBorderActive)";

            /// <summary />
            public const string BrassForeground2 = "var(--colorPaletteBrassForeground2)";

            /// <summary />
            public const string BrownBackground2 = "var(--colorPaletteBrownBackground2)";

            /// <summary />
            public const string BrownBorderActive = "var(--colorPaletteBrownBorderActive)";

            /// <summary />
            public const string BrownForeground2 = "var(--colorPaletteBrownForeground2)";

            /// <summary />
            public const string CornflowerBackground2 = "var(--colorPaletteCornflowerBackground2)";

            /// <summary />
            public const string CornflowerBorderActive = "var(--colorPaletteCornflowerBorderActive)";

            /// <summary />
            public const string CornflowerForeground2 = "var(--colorPaletteCornflowerForeground2)";

            /// <summary />
            public const string CranberryBackground2 = "var(--colorPaletteCranberryBackground2)";

            /// <summary />
            public const string CranberryBorderActive = "var(--colorPaletteCranberryBorderActive)";

            /// <summary />
            public const string CranberryForeground2 = "var(--colorPaletteCranberryForeground2)";

            /// <summary />
            public const string DarkGreenBackground2 = "var(--colorPaletteDarkGreenBackground2)";

            /// <summary />
            public const string DarkGreenBorderActive = "var(--colorPaletteDarkGreenBorderActive)";

            /// <summary />
            public const string DarkGreenForeground2 = "var(--colorPaletteDarkGreenForeground2)";

            /// <summary />
            public const string DarkOrangeBackground1 = "var(--colorPaletteDarkOrangeBackground1)";

            /// <summary />
            public const string DarkOrangeBackground2 = "var(--colorPaletteDarkOrangeBackground2)";

            /// <summary />
            public const string DarkOrangeBackground3 = "var(--colorPaletteDarkOrangeBackground3)";

            /// <summary />
            public const string DarkOrangeBorder1 = "var(--colorPaletteDarkOrangeBorder1)";

            /// <summary />
            public const string DarkOrangeBorder2 = "var(--colorPaletteDarkOrangeBorder2)";

            /// <summary />
            public const string DarkOrangeBorderActive = "var(--colorPaletteDarkOrangeBorderActive)";

            /// <summary />
            public const string DarkOrangeForeground1 = "var(--colorPaletteDarkOrangeForeground1)";

            /// <summary />
            public const string DarkOrangeForeground2 = "var(--colorPaletteDarkOrangeForeground2)";

            /// <summary />
            public const string DarkOrangeForeground3 = "var(--colorPaletteDarkOrangeForeground3)";

            /// <summary />
            public const string DarkRedBackground2 = "var(--colorPaletteDarkRedBackground2)";

            /// <summary />
            public const string DarkRedBorderActive = "var(--colorPaletteDarkRedBorderActive)";

            /// <summary />
            public const string DarkRedForeground2 = "var(--colorPaletteDarkRedForeground2)";

            /// <summary />
            public const string ForestBackground2 = "var(--colorPaletteForestBackground2)";

            /// <summary />
            public const string ForestBorderActive = "var(--colorPaletteForestBorderActive)";

            /// <summary />
            public const string ForestForeground2 = "var(--colorPaletteForestForeground2)";

            /// <summary />
            public const string GoldBackground2 = "var(--colorPaletteGoldBackground2)";

            /// <summary />
            public const string GoldBorderActive = "var(--colorPaletteGoldBorderActive)";

            /// <summary />
            public const string GoldForeground2 = "var(--colorPaletteGoldForeground2)";

            /// <summary />
            public const string GrapeBackground2 = "var(--colorPaletteGrapeBackground2)";

            /// <summary />
            public const string GrapeBorderActive = "var(--colorPaletteGrapeBorderActive)";

            /// <summary />
            public const string GrapeForeground2 = "var(--colorPaletteGrapeForeground2)";

            /// <summary />
            public const string GreenBackground1 = "var(--colorPaletteGreenBackground1)";

            /// <summary />
            public const string GreenBackground2 = "var(--colorPaletteGreenBackground2)";

            /// <summary />
            public const string GreenBackground3 = "var(--colorPaletteGreenBackground3)";

            /// <summary />
            public const string GreenBorder1 = "var(--colorPaletteGreenBorder1)";

            /// <summary />
            public const string GreenBorder2 = "var(--colorPaletteGreenBorder2)";

            /// <summary />
            public const string GreenBorderActive = "var(--colorPaletteGreenBorderActive)";

            /// <summary />
            public const string GreenForeground1 = "var(--colorPaletteGreenForeground1)";

            /// <summary />
            public const string GreenForeground2 = "var(--colorPaletteGreenForeground2)";

            /// <summary />
            public const string GreenForeground3 = "var(--colorPaletteGreenForeground3)";

            /// <summary />
            public const string GreenForegroundInverted = "var(--colorPaletteGreenForegroundInverted)";

            /// <summary />
            public const string LavenderBackground2 = "var(--colorPaletteLavenderBackground2)";

            /// <summary />
            public const string LavenderBorderActive = "var(--colorPaletteLavenderBorderActive)";

            /// <summary />
            public const string LavenderForeground2 = "var(--colorPaletteLavenderForeground2)";

            /// <summary />
            public const string LightGreenBackground1 = "var(--colorPaletteLightGreenBackground1)";

            /// <summary />
            public const string LightGreenBackground2 = "var(--colorPaletteLightGreenBackground2)";

            /// <summary />
            public const string LightGreenBackground3 = "var(--colorPaletteLightGreenBackground3)";

            /// <summary />
            public const string LightGreenBorder1 = "var(--colorPaletteLightGreenBorder1)";

            /// <summary />
            public const string LightGreenBorder2 = "var(--colorPaletteLightGreenBorder2)";

            /// <summary />
            public const string LightGreenBorderActive = "var(--colorPaletteLightGreenBorderActive)";

            /// <summary />
            public const string LightGreenForeground1 = "var(--colorPaletteLightGreenForeground1)";

            /// <summary />
            public const string LightGreenForeground2 = "var(--colorPaletteLightGreenForeground2)";

            /// <summary />
            public const string LightGreenForeground3 = "var(--colorPaletteLightGreenForeground3)";

            /// <summary />
            public const string LightTealBackground2 = "var(--colorPaletteLightTealBackground2)";

            /// <summary />
            public const string LightTealBorderActive = "var(--colorPaletteLightTealBorderActive)";

            /// <summary />
            public const string LightTealForeground2 = "var(--colorPaletteLightTealForeground2)";

            /// <summary />
            public const string LilacBackground2 = "var(--colorPaletteLilacBackground2)";

            /// <summary />
            public const string LilacBorderActive = "var(--colorPaletteLilacBorderActive)";

            /// <summary />
            public const string LilacForeground2 = "var(--colorPaletteLilacForeground2)";

            /// <summary />
            public const string MagentaBackground2 = "var(--colorPaletteMagentaBackground2)";

            /// <summary />
            public const string MagentaBorderActive = "var(--colorPaletteMagentaBorderActive)";

            /// <summary />
            public const string MagentaForeground2 = "var(--colorPaletteMagentaForeground2)";

            /// <summary />
            public const string MarigoldBackground1 = "var(--colorPaletteMarigoldBackground1)";

            /// <summary />
            public const string MarigoldBackground2 = "var(--colorPaletteMarigoldBackground2)";

            /// <summary />
            public const string MarigoldBackground3 = "var(--colorPaletteMarigoldBackground3)";

            /// <summary />
            public const string MarigoldBorder1 = "var(--colorPaletteMarigoldBorder1)";

            /// <summary />
            public const string MarigoldBorder2 = "var(--colorPaletteMarigoldBorder2)";

            /// <summary />
            public const string MarigoldBorderActive = "var(--colorPaletteMarigoldBorderActive)";

            /// <summary />
            public const string MarigoldForeground1 = "var(--colorPaletteMarigoldForeground1)";

            /// <summary />
            public const string MarigoldForeground2 = "var(--colorPaletteMarigoldForeground2)";

            /// <summary />
            public const string MarigoldForeground3 = "var(--colorPaletteMarigoldForeground3)";

            /// <summary />
            public const string MinkBackground2 = "var(--colorPaletteMinkBackground2)";

            /// <summary />
            public const string MinkBorderActive = "var(--colorPaletteMinkBorderActive)";

            /// <summary />
            public const string MinkForeground2 = "var(--colorPaletteMinkForeground2)";

            /// <summary />
            public const string NavyBackground2 = "var(--colorPaletteNavyBackground2)";

            /// <summary />
            public const string NavyBorderActive = "var(--colorPaletteNavyBorderActive)";

            /// <summary />
            public const string NavyForeground2 = "var(--colorPaletteNavyForeground2)";

            /// <summary />
            public const string PeachBackground2 = "var(--colorPalettePeachBackground2)";

            /// <summary />
            public const string PeachBorderActive = "var(--colorPalettePeachBorderActive)";

            /// <summary />
            public const string PeachForeground2 = "var(--colorPalettePeachForeground2)";

            /// <summary />
            public const string PinkBackground2 = "var(--colorPalettePinkBackground2)";

            /// <summary />
            public const string PinkBorderActive = "var(--colorPalettePinkBorderActive)";

            /// <summary />
            public const string PinkForeground2 = "var(--colorPalettePinkForeground2)";

            /// <summary />
            public const string PlatinumBackground2 = "var(--colorPalettePlatinumBackground2)";

            /// <summary />
            public const string PlatinumBorderActive = "var(--colorPalettePlatinumBorderActive)";

            /// <summary />
            public const string PlatinumForeground2 = "var(--colorPalettePlatinumForeground2)";

            /// <summary />
            public const string PlumBackground2 = "var(--colorPalettePlumBackground2)";

            /// <summary />
            public const string PlumBorderActive = "var(--colorPalettePlumBorderActive)";

            /// <summary />
            public const string PlumForeground2 = "var(--colorPalettePlumForeground2)";

            /// <summary />
            public const string PumpkinBackground2 = "var(--colorPalettePumpkinBackground2)";

            /// <summary />
            public const string PumpkinBorderActive = "var(--colorPalettePumpkinBorderActive)";

            /// <summary />
            public const string PumpkinForeground2 = "var(--colorPalettePumpkinForeground2)";

            /// <summary />
            public const string PurpleBackground2 = "var(--colorPalettePurpleBackground2)";

            /// <summary />
            public const string PurpleBorderActive = "var(--colorPalettePurpleBorderActive)";

            /// <summary />
            public const string PurpleForeground2 = "var(--colorPalettePurpleForeground2)";

            /// <summary />
            public const string RedBackground1 = "var(--colorPaletteRedBackground1)";

            /// <summary />
            public const string RedBackground2 = "var(--colorPaletteRedBackground2)";

            /// <summary />
            public const string RedBackground3 = "var(--colorPaletteRedBackground3)";

            /// <summary />
            public const string RedBorder1 = "var(--colorPaletteRedBorder1)";

            /// <summary />
            public const string RedBorder2 = "var(--colorPaletteRedBorder2)";

            /// <summary />
            public const string RedBorderActive = "var(--colorPaletteRedBorderActive)";

            /// <summary />
            public const string RedForeground1 = "var(--colorPaletteRedForeground1)";

            /// <summary />
            public const string RedForeground2 = "var(--colorPaletteRedForeground2)";

            /// <summary />
            public const string RedForeground3 = "var(--colorPaletteRedForeground3)";

            /// <summary />
            public const string RedForegroundInverted = "var(--colorPaletteRedForegroundInverted)";

            /// <summary />
            public const string RoyalBlueBackground2 = "var(--colorPaletteRoyalBlueBackground2)";

            /// <summary />
            public const string RoyalBlueBorderActive = "var(--colorPaletteRoyalBlueBorderActive)";

            /// <summary />
            public const string RoyalBlueForeground2 = "var(--colorPaletteRoyalBlueForeground2)";

            /// <summary />
            public const string SeafoamBackground2 = "var(--colorPaletteSeafoamBackground2)";

            /// <summary />
            public const string SeafoamBorderActive = "var(--colorPaletteSeafoamBorderActive)";

            /// <summary />
            public const string SeafoamForeground2 = "var(--colorPaletteSeafoamForeground2)";

            /// <summary />
            public const string SteelBackground2 = "var(--colorPaletteSteelBackground2)";

            /// <summary />
            public const string SteelBorderActive = "var(--colorPaletteSteelBorderActive)";

            /// <summary />
            public const string SteelForeground2 = "var(--colorPaletteSteelForeground2)";

            /// <summary />
            public const string TealBackground2 = "var(--colorPaletteTealBackground2)";

            /// <summary />
            public const string TealBorderActive = "var(--colorPaletteTealBorderActive)";

            /// <summary />
            public const string TealForeground2 = "var(--colorPaletteTealForeground2)";

            /// <summary />
            public const string YellowBackground1 = "var(--colorPaletteYellowBackground1)";

            /// <summary />
            public const string YellowBackground2 = "var(--colorPaletteYellowBackground2)";

            /// <summary />
            public const string YellowBackground3 = "var(--colorPaletteYellowBackground3)";

            /// <summary />
            public const string YellowBorder1 = "var(--colorPaletteYellowBorder1)";

            /// <summary />
            public const string YellowBorder2 = "var(--colorPaletteYellowBorder2)";

            /// <summary />
            public const string YellowBorderActive = "var(--colorPaletteYellowBorderActive)";

            /// <summary />
            public const string YellowForeground1 = "var(--colorPaletteYellowForeground1)";

            /// <summary />
            public const string YellowForeground2 = "var(--colorPaletteYellowForeground2)";

            /// <summary />
            public const string YellowForeground3 = "var(--colorPaletteYellowForeground3)";

            /// <summary />
            public const string YellowForegroundInverted = "var(--colorPaletteYellowForegroundInverted)";

        }
        /// <summary />
        public partial class Background
        {
            /// <summary />
            public const string Overlay = "var(--colorBackgroundOverlay)";

        }
        /// <summary />
        public partial class Stroke
        {
            /// <summary />
            public const string Focus1 = "var(--colorStrokeFocus1)";

            /// <summary />
            public const string Focus2 = "var(--colorStrokeFocus2)";

        }
        /// <summary />
        public partial class Transparent
        {
            /// <summary />
            public const string Background = "var(--colorTransparentBackground)";

            /// <summary />
            public const string BackgroundHover = "var(--colorTransparentBackgroundHover)";

            /// <summary />
            public const string BackgroundPressed = "var(--colorTransparentBackgroundPressed)";

            /// <summary />
            public const string BackgroundSelected = "var(--colorTransparentBackgroundSelected)";

            /// <summary />
            public const string Stroke = "var(--colorTransparentStroke)";

            /// <summary />
            public const string StrokeDisabled = "var(--colorTransparentStrokeDisabled)";

            /// <summary />
            public const string StrokeInteractive = "var(--colorTransparentStrokeInteractive)";

        }
        /// <summary />
        public partial class Neutral
        {
            /// <summary />
            public const string Background1 = "var(--colorNeutralBackground1)";

            /// <summary />
            public const string Background1Hover = "var(--colorNeutralBackground1Hover)";

            /// <summary />
            public const string Background1Pressed = "var(--colorNeutralBackground1Pressed)";

            /// <summary />
            public const string Background1Selected = "var(--colorNeutralBackground1Selected)";

            /// <summary />
            public const string Background2 = "var(--colorNeutralBackground2)";

            /// <summary />
            public const string Background2Hover = "var(--colorNeutralBackground2Hover)";

            /// <summary />
            public const string Background2Pressed = "var(--colorNeutralBackground2Pressed)";

            /// <summary />
            public const string Background2Selected = "var(--colorNeutralBackground2Selected)";

            /// <summary />
            public const string Background3 = "var(--colorNeutralBackground3)";

            /// <summary />
            public const string Background3Hover = "var(--colorNeutralBackground3Hover)";

            /// <summary />
            public const string Background3Pressed = "var(--colorNeutralBackground3Pressed)";

            /// <summary />
            public const string Background3Selected = "var(--colorNeutralBackground3Selected)";

            /// <summary />
            public const string Background4 = "var(--colorNeutralBackground4)";

            /// <summary />
            public const string Background4Hover = "var(--colorNeutralBackground4Hover)";

            /// <summary />
            public const string Background4Pressed = "var(--colorNeutralBackground4Pressed)";

            /// <summary />
            public const string Background4Selected = "var(--colorNeutralBackground4Selected)";

            /// <summary />
            public const string Background5 = "var(--colorNeutralBackground5)";

            /// <summary />
            public const string Background5Hover = "var(--colorNeutralBackground5Hover)";

            /// <summary />
            public const string Background5Pressed = "var(--colorNeutralBackground5Pressed)";

            /// <summary />
            public const string Background5Selected = "var(--colorNeutralBackground5Selected)";

            /// <summary />
            public const string Background6 = "var(--colorNeutralBackground6)";

            /// <summary />
            public const string BackgroundAlpha = "var(--colorNeutralBackgroundAlpha)";

            /// <summary />
            public const string BackgroundAlpha2 = "var(--colorNeutralBackgroundAlpha2)";

            /// <summary />
            public const string BackgroundDisabled = "var(--colorNeutralBackgroundDisabled)";

            /// <summary />
            public const string BackgroundInverted = "var(--colorNeutralBackgroundInverted)";

            /// <summary />
            public const string BackgroundInvertedDisabled = "var(--colorNeutralBackgroundInvertedDisabled)";

            /// <summary />
            public const string BackgroundStatic = "var(--colorNeutralBackgroundStatic)";

            /// <summary />
            public const string CardBackground = "var(--colorNeutralCardBackground)";

            /// <summary />
            public const string CardBackgroundDisabled = "var(--colorNeutralCardBackgroundDisabled)";

            /// <summary />
            public const string CardBackgroundHover = "var(--colorNeutralCardBackgroundHover)";

            /// <summary />
            public const string CardBackgroundPressed = "var(--colorNeutralCardBackgroundPressed)";

            /// <summary />
            public const string CardBackgroundSelected = "var(--colorNeutralCardBackgroundSelected)";

            /// <summary />
            public const string Foreground1 = "var(--colorNeutralForeground1)";

            /// <summary />
            public const string Foreground1Hover = "var(--colorNeutralForeground1Hover)";

            /// <summary />
            public const string Foreground1Pressed = "var(--colorNeutralForeground1Pressed)";

            /// <summary />
            public const string Foreground1Selected = "var(--colorNeutralForeground1Selected)";

            /// <summary />
            public const string Foreground1Static = "var(--colorNeutralForeground1Static)";

            /// <summary />
            public const string Foreground2 = "var(--colorNeutralForeground2)";

            /// <summary />
            public const string Foreground2BrandHover = "var(--colorNeutralForeground2BrandHover)";

            /// <summary />
            public const string Foreground2BrandPressed = "var(--colorNeutralForeground2BrandPressed)";

            /// <summary />
            public const string Foreground2BrandSelected = "var(--colorNeutralForeground2BrandSelected)";

            /// <summary />
            public const string Foreground2Hover = "var(--colorNeutralForeground2Hover)";

            /// <summary />
            public const string Foreground2Link = "var(--colorNeutralForeground2Link)";

            /// <summary />
            public const string Foreground2LinkHover = "var(--colorNeutralForeground2LinkHover)";

            /// <summary />
            public const string Foreground2LinkPressed = "var(--colorNeutralForeground2LinkPressed)";

            /// <summary />
            public const string Foreground2LinkSelected = "var(--colorNeutralForeground2LinkSelected)";

            /// <summary />
            public const string Foreground2Pressed = "var(--colorNeutralForeground2Pressed)";

            /// <summary />
            public const string Foreground2Selected = "var(--colorNeutralForeground2Selected)";

            /// <summary />
            public const string Foreground3 = "var(--colorNeutralForeground3)";

            /// <summary />
            public const string Foreground3BrandHover = "var(--colorNeutralForeground3BrandHover)";

            /// <summary />
            public const string Foreground3BrandPressed = "var(--colorNeutralForeground3BrandPressed)";

            /// <summary />
            public const string Foreground3BrandSelected = "var(--colorNeutralForeground3BrandSelected)";

            /// <summary />
            public const string Foreground3Hover = "var(--colorNeutralForeground3Hover)";

            /// <summary />
            public const string Foreground3Pressed = "var(--colorNeutralForeground3Pressed)";

            /// <summary />
            public const string Foreground3Selected = "var(--colorNeutralForeground3Selected)";

            /// <summary />
            public const string Foreground4 = "var(--colorNeutralForeground4)";

            /// <summary />
            public const string ForegroundDisabled = "var(--colorNeutralForegroundDisabled)";

            /// <summary />
            public const string ForegroundInverted = "var(--colorNeutralForegroundInverted)";

            /// <summary />
            public const string ForegroundInverted2 = "var(--colorNeutralForegroundInverted2)";

            /// <summary />
            public const string ForegroundInvertedDisabled = "var(--colorNeutralForegroundInvertedDisabled)";

            /// <summary />
            public const string ForegroundInvertedHover = "var(--colorNeutralForegroundInvertedHover)";

            /// <summary />
            public const string ForegroundInvertedLink = "var(--colorNeutralForegroundInvertedLink)";

            /// <summary />
            public const string ForegroundInvertedLinkHover = "var(--colorNeutralForegroundInvertedLinkHover)";

            /// <summary />
            public const string ForegroundInvertedLinkPressed = "var(--colorNeutralForegroundInvertedLinkPressed)";

            /// <summary />
            public const string ForegroundInvertedLinkSelected = "var(--colorNeutralForegroundInvertedLinkSelected)";

            /// <summary />
            public const string ForegroundInvertedPressed = "var(--colorNeutralForegroundInvertedPressed)";

            /// <summary />
            public const string ForegroundInvertedSelected = "var(--colorNeutralForegroundInvertedSelected)";

            /// <summary />
            public const string ForegroundOnBrand = "var(--colorNeutralForegroundOnBrand)";

            /// <summary />
            public const string ForegroundStaticInverted = "var(--colorNeutralForegroundStaticInverted)";

            /// <summary />
            public const string ShadowAmbient = "var(--colorNeutralShadowAmbient)";

            /// <summary />
            public const string ShadowAmbientDarker = "var(--colorNeutralShadowAmbientDarker)";

            /// <summary />
            public const string ShadowAmbientLighter = "var(--colorNeutralShadowAmbientLighter)";

            /// <summary />
            public const string ShadowKey = "var(--colorNeutralShadowKey)";

            /// <summary />
            public const string ShadowKeyDarker = "var(--colorNeutralShadowKeyDarker)";

            /// <summary />
            public const string ShadowKeyLighter = "var(--colorNeutralShadowKeyLighter)";

            /// <summary />
            public const string Stencil1 = "var(--colorNeutralStencil1)";

            /// <summary />
            public const string Stencil1Alpha = "var(--colorNeutralStencil1Alpha)";

            /// <summary />
            public const string Stencil2 = "var(--colorNeutralStencil2)";

            /// <summary />
            public const string Stencil2Alpha = "var(--colorNeutralStencil2Alpha)";

            /// <summary />
            public const string Stroke1 = "var(--colorNeutralStroke1)";

            /// <summary />
            public const string Stroke1Hover = "var(--colorNeutralStroke1Hover)";

            /// <summary />
            public const string Stroke1Pressed = "var(--colorNeutralStroke1Pressed)";

            /// <summary />
            public const string Stroke1Selected = "var(--colorNeutralStroke1Selected)";

            /// <summary />
            public const string Stroke2 = "var(--colorNeutralStroke2)";

            /// <summary />
            public const string Stroke3 = "var(--colorNeutralStroke3)";

            /// <summary />
            public const string StrokeAccessible = "var(--colorNeutralStrokeAccessible)";

            /// <summary />
            public const string StrokeAccessibleHover = "var(--colorNeutralStrokeAccessibleHover)";

            /// <summary />
            public const string StrokeAccessiblePressed = "var(--colorNeutralStrokeAccessiblePressed)";

            /// <summary />
            public const string StrokeAccessibleSelected = "var(--colorNeutralStrokeAccessibleSelected)";

            /// <summary />
            public const string StrokeAlpha = "var(--colorNeutralStrokeAlpha)";

            /// <summary />
            public const string StrokeAlpha2 = "var(--colorNeutralStrokeAlpha2)";

            /// <summary />
            public const string StrokeDisabled = "var(--colorNeutralStrokeDisabled)";

            /// <summary />
            public const string StrokeInvertedDisabled = "var(--colorNeutralStrokeInvertedDisabled)";

            /// <summary />
            public const string StrokeOnBrand = "var(--colorNeutralStrokeOnBrand)";

            /// <summary />
            public const string StrokeOnBrand2 = "var(--colorNeutralStrokeOnBrand2)";

            /// <summary />
            public const string StrokeOnBrand2Hover = "var(--colorNeutralStrokeOnBrand2Hover)";

            /// <summary />
            public const string StrokeOnBrand2Pressed = "var(--colorNeutralStrokeOnBrand2Pressed)";

            /// <summary />
            public const string StrokeOnBrand2Selected = "var(--colorNeutralStrokeOnBrand2Selected)";

            /// <summary />
            public const string StrokeSubtle = "var(--colorNeutralStrokeSubtle)";

        }
        /// <summary />
        public partial class Brand
        {
            /// <summary />
            public const string Background = "var(--colorBrandBackground)";

            /// <summary />
            public const string Background2 = "var(--colorBrandBackground2)";

            /// <summary />
            public const string Background2Hover = "var(--colorBrandBackground2Hover)";

            /// <summary />
            public const string Background2Pressed = "var(--colorBrandBackground2Pressed)";

            /// <summary />
            public const string Background3Static = "var(--colorBrandBackground3Static)";

            /// <summary />
            public const string Background4Static = "var(--colorBrandBackground4Static)";

            /// <summary />
            public const string BackgroundHover = "var(--colorBrandBackgroundHover)";

            /// <summary />
            public const string BackgroundInverted = "var(--colorBrandBackgroundInverted)";

            /// <summary />
            public const string BackgroundInvertedHover = "var(--colorBrandBackgroundInvertedHover)";

            /// <summary />
            public const string BackgroundInvertedPressed = "var(--colorBrandBackgroundInvertedPressed)";

            /// <summary />
            public const string BackgroundInvertedSelected = "var(--colorBrandBackgroundInvertedSelected)";

            /// <summary />
            public const string BackgroundPressed = "var(--colorBrandBackgroundPressed)";

            /// <summary />
            public const string BackgroundSelected = "var(--colorBrandBackgroundSelected)";

            /// <summary />
            public const string BackgroundStatic = "var(--colorBrandBackgroundStatic)";

            /// <summary />
            public const string Foreground1 = "var(--colorBrandForeground1)";

            /// <summary />
            public const string Foreground2 = "var(--colorBrandForeground2)";

            /// <summary />
            public const string Foreground2Hover = "var(--colorBrandForeground2Hover)";

            /// <summary />
            public const string Foreground2Pressed = "var(--colorBrandForeground2Pressed)";

            /// <summary />
            public const string ForegroundInverted = "var(--colorBrandForegroundInverted)";

            /// <summary />
            public const string ForegroundInvertedHover = "var(--colorBrandForegroundInvertedHover)";

            /// <summary />
            public const string ForegroundInvertedPressed = "var(--colorBrandForegroundInvertedPressed)";

            /// <summary />
            public const string ForegroundLink = "var(--colorBrandForegroundLink)";

            /// <summary />
            public const string ForegroundLinkHover = "var(--colorBrandForegroundLinkHover)";

            /// <summary />
            public const string ForegroundLinkPressed = "var(--colorBrandForegroundLinkPressed)";

            /// <summary />
            public const string ForegroundLinkSelected = "var(--colorBrandForegroundLinkSelected)";

            /// <summary />
            public const string ForegroundOnLight = "var(--colorBrandForegroundOnLight)";

            /// <summary />
            public const string ForegroundOnLightHover = "var(--colorBrandForegroundOnLightHover)";

            /// <summary />
            public const string ForegroundOnLightPressed = "var(--colorBrandForegroundOnLightPressed)";

            /// <summary />
            public const string ForegroundOnLightSelected = "var(--colorBrandForegroundOnLightSelected)";

            /// <summary />
            public const string ShadowAmbient = "var(--colorBrandShadowAmbient)";

            /// <summary />
            public const string ShadowKey = "var(--colorBrandShadowKey)";

            /// <summary />
            public const string Stroke1 = "var(--colorBrandStroke1)";

            /// <summary />
            public const string Stroke2 = "var(--colorBrandStroke2)";

            /// <summary />
            public const string Stroke2Contrast = "var(--colorBrandStroke2Contrast)";

            /// <summary />
            public const string Stroke2Hover = "var(--colorBrandStroke2Hover)";

            /// <summary />
            public const string Stroke2Pressed = "var(--colorBrandStroke2Pressed)";

        }
        /// <summary />
        public partial class Status
        {
            /// <summary />
            public const string DangerBackground1 = "var(--colorStatusDangerBackground1)";

            /// <summary />
            public const string DangerBackground2 = "var(--colorStatusDangerBackground2)";

            /// <summary />
            public const string DangerBackground3 = "var(--colorStatusDangerBackground3)";

            /// <summary />
            public const string DangerBackground3Hover = "var(--colorStatusDangerBackground3Hover)";

            /// <summary />
            public const string DangerBackground3Pressed = "var(--colorStatusDangerBackground3Pressed)";

            /// <summary />
            public const string DangerBorder1 = "var(--colorStatusDangerBorder1)";

            /// <summary />
            public const string DangerBorder2 = "var(--colorStatusDangerBorder2)";

            /// <summary />
            public const string DangerBorderActive = "var(--colorStatusDangerBorderActive)";

            /// <summary />
            public const string DangerForeground1 = "var(--colorStatusDangerForeground1)";

            /// <summary />
            public const string DangerForeground2 = "var(--colorStatusDangerForeground2)";

            /// <summary />
            public const string DangerForeground3 = "var(--colorStatusDangerForeground3)";

            /// <summary />
            public const string DangerForegroundInverted = "var(--colorStatusDangerForegroundInverted)";

            /// <summary />
            public const string SuccessBackground1 = "var(--colorStatusSuccessBackground1)";

            /// <summary />
            public const string SuccessBackground2 = "var(--colorStatusSuccessBackground2)";

            /// <summary />
            public const string SuccessBackground3 = "var(--colorStatusSuccessBackground3)";

            /// <summary />
            public const string SuccessBorder1 = "var(--colorStatusSuccessBorder1)";

            /// <summary />
            public const string SuccessBorder2 = "var(--colorStatusSuccessBorder2)";

            /// <summary />
            public const string SuccessBorderActive = "var(--colorStatusSuccessBorderActive)";

            /// <summary />
            public const string SuccessForeground1 = "var(--colorStatusSuccessForeground1)";

            /// <summary />
            public const string SuccessForeground2 = "var(--colorStatusSuccessForeground2)";

            /// <summary />
            public const string SuccessForeground3 = "var(--colorStatusSuccessForeground3)";

            /// <summary />
            public const string SuccessForegroundInverted = "var(--colorStatusSuccessForegroundInverted)";

            /// <summary />
            public const string WarningBackground1 = "var(--colorStatusWarningBackground1)";

            /// <summary />
            public const string WarningBackground2 = "var(--colorStatusWarningBackground2)";

            /// <summary />
            public const string WarningBackground3 = "var(--colorStatusWarningBackground3)";

            /// <summary />
            public const string WarningBorder1 = "var(--colorStatusWarningBorder1)";

            /// <summary />
            public const string WarningBorder2 = "var(--colorStatusWarningBorder2)";

            /// <summary />
            public const string WarningBorderActive = "var(--colorStatusWarningBorderActive)";

            /// <summary />
            public const string WarningForeground1 = "var(--colorStatusWarningForeground1)";

            /// <summary />
            public const string WarningForeground2 = "var(--colorStatusWarningForeground2)";

            /// <summary />
            public const string WarningForeground3 = "var(--colorStatusWarningForeground3)";

            /// <summary />
            public const string WarningForegroundInverted = "var(--colorStatusWarningForegroundInverted)";

        }
        /// <summary />
        public partial class Compound
        {
            /// <summary />
            public const string BrandBackground = "var(--colorCompoundBrandBackground)";

            /// <summary />
            public const string BrandBackgroundHover = "var(--colorCompoundBrandBackgroundHover)";

            /// <summary />
            public const string BrandBackgroundPressed = "var(--colorCompoundBrandBackgroundPressed)";

            /// <summary />
            public const string BrandForeground1 = "var(--colorCompoundBrandForeground1)";

            /// <summary />
            public const string BrandForeground1Hover = "var(--colorCompoundBrandForeground1Hover)";

            /// <summary />
            public const string BrandForeground1Pressed = "var(--colorCompoundBrandForeground1Pressed)";

            /// <summary />
            public const string BrandStroke = "var(--colorCompoundBrandStroke)";

            /// <summary />
            public const string BrandStrokeHover = "var(--colorCompoundBrandStrokeHover)";

            /// <summary />
            public const string BrandStrokePressed = "var(--colorCompoundBrandStrokePressed)";

        }
        /// <summary />
        public partial class Scrollbar
        {
            /// <summary />
            public const string Overlay = "var(--colorScrollbarOverlay)";

        }
    }
    /// <summary />
    public partial class Lines
    {
        /// <summary />
        public partial class Height
        {
            /// <summary />
            public const string Base100 = "var(--lineHeightBase100)";

            /// <summary />
            public const string Base200 = "var(--lineHeightBase200)";

            /// <summary />
            public const string Base300 = "var(--lineHeightBase300)";

            /// <summary />
            public const string Base400 = "var(--lineHeightBase400)";

            /// <summary />
            public const string Base500 = "var(--lineHeightBase500)";

            /// <summary />
            public const string Base600 = "var(--lineHeightBase600)";

            /// <summary />
            public const string Hero1000 = "var(--lineHeightHero1000)";

            /// <summary />
            public const string Hero700 = "var(--lineHeightHero700)";

            /// <summary />
            public const string Hero800 = "var(--lineHeightHero800)";

            /// <summary />
            public const string Hero900 = "var(--lineHeightHero900)";

        }
    }
    /// <summary />
    public partial class Spacings
    {
        /// <summary />
        public partial class Vertical
        {
            /// <summary />
            public const string L = "var(--spacingVerticalL)";

            /// <summary />
            public const string M = "var(--spacingVerticalM)";

            /// <summary />
            public const string MNudge = "var(--spacingVerticalMNudge)";

            /// <summary />
            public const string None = "var(--spacingVerticalNone)";

            /// <summary />
            public const string S = "var(--spacingVerticalS)";

            /// <summary />
            public const string SNudge = "var(--spacingVerticalSNudge)";

            /// <summary />
            public const string XL = "var(--spacingVerticalXL)";

            /// <summary />
            public const string XS = "var(--spacingVerticalXS)";

            /// <summary />
            public const string XXL = "var(--spacingVerticalXXL)";

            /// <summary />
            public const string XXS = "var(--spacingVerticalXXS)";

            /// <summary />
            public const string XXXL = "var(--spacingVerticalXXXL)";

        }
        /// <summary />
        public partial class Horizontal
        {
            /// <summary />
            public const string L = "var(--spacingHorizontalL)";

            /// <summary />
            public const string M = "var(--spacingHorizontalM)";

            /// <summary />
            public const string MNudge = "var(--spacingHorizontalMNudge)";

            /// <summary />
            public const string None = "var(--spacingHorizontalNone)";

            /// <summary />
            public const string S = "var(--spacingHorizontalS)";

            /// <summary />
            public const string SNudge = "var(--spacingHorizontalSNudge)";

            /// <summary />
            public const string XL = "var(--spacingHorizontalXL)";

            /// <summary />
            public const string XS = "var(--spacingHorizontalXS)";

            /// <summary />
            public const string XXL = "var(--spacingHorizontalXXL)";

            /// <summary />
            public const string XXS = "var(--spacingHorizontalXXS)";

            /// <summary />
            public const string XXXL = "var(--spacingHorizontalXXXL)";

        }
    }
}
