// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable 1591

namespace Microsoft.Fast.Components.FluentUI;

internal static partial class CoreIcons
{
}

#pragma warning restore 1591
