import * as esbuild from 'esbuild'
import { glob } from 'glob'
import { writeFile, unlink } from 'fs/promises';
import pkg from './package.json' with { type: 'json' }
import fs from "fs";
import path from "path";

// Generate BuildConstants.ts with BUILD_MODE constant based on --build-mode argument
const rawBuildMode = process.argv.find(a => a.startsWith('--build-mode='))?.split('=')[1];
const buildMode = rawBuildMode === "Release" ? "Release" : "Debug";

const constantsFile = path.resolve("src/BuildConstants.ts");
const constantsContent = `// This file is generated by a tool. Do not change!\nexport const BUILD_MODE = '${buildMode}';\n`;
const isNotCurrentMode = !fs.existsSync(constantsFile) || !fs.readFileSync(constantsFile, 'utf-8').includes(`BUILD_MODE = '${buildMode}'`);
if (isNotCurrentMode) {
    fs.writeFileSync(constantsFile, constantsContent);
}

// JS: Microsoft.FluentUI.AspNetCore.Components.Charts.lib.module.js
await esbuild.build({
    entryPoints: [pkg.source],
    bundle: true,
    minify: buildMode !== "Debug",
    sourcemap: buildMode === "Debug",
    logLevel: 'info',
    target: 'es2022',
    format: 'esm',
    outfile: pkg.main,
    legalComments: 'none'
});

// CSS: Microsoft.FluentUI.AspNetCore.Components.Charts.bundle.scp.css
const allStyleFile = 'all-styles.css';
const files = await glob(pkg.cssFiles);
const content = files.map(file => `@import "${file.replace(/\\/g, '/')}";`).join('\n');

await writeFile(allStyleFile, content);
await esbuild.build({
    entryPoints: [allStyleFile],
    loader: { '.css': 'css' },
    outfile: pkg.cssBundle,
    bundle: true,
    minify: true,
    sourcemap: false,
});
await unlink(allStyleFile);
