using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.FluentUI.AspNetCore.Components.Generators;

[Generator]
public sealed class EnumAttributeValueGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static production => production.AddSource("EnumAttributeValuesAttribute.g.cs", """
            // <auto-generated/>
            namespace Microsoft.FluentUI.AspNetCore.Components.Generators;

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
            internal sealed class EnumAttributeValuesAttribute : global::System.Attribute
            {
                public EnumAttributeValuesAttribute(global::System.Type enumType) { }
            }
            """));

        var contexts = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Microsoft.FluentUI.AspNetCore.Components.Generators.EnumAttributeValuesAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntax, _) => syntax);

        context.RegisterSourceOutput(contexts, static (production, input) =>
        {
            var contextType = (INamedTypeSymbol)input.TargetSymbol;
            var types = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var attribute in input.Attributes)
            {
                if (attribute.ConstructorArguments.Length != 1 ||
                    attribute.ConstructorArguments[0].Value is not INamedTypeSymbol { TypeKind: TypeKind.Enum } enumType)
                {
                    continue;
                }

                types.Add(enumType);
            }

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");
            source.AppendLine("#pragma warning disable CS0612, CS0618");
            source.Append("namespace ").Append(contextType.ContainingNamespace.ToDisplayString()).AppendLine(";");
            source.Append("internal static partial class ").Append(contextType.Name).AppendLine();
            source.AppendLine("{");
            foreach (var enumType in types.OrderBy(symbol => symbol.ToDisplayString(), StringComparer.Ordinal))
            {
                AppendEnum(source, enumType);
            }

            source.AppendLine("}");
            production.AddSource(contextType.ToDisplayString() + ".g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }

    private static void AppendEnum(StringBuilder source, INamedTypeSymbol enumType)
    {
        var typeName = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        source.Append("    internal static string? ToAttributeValue(this ").Append(typeName).AppendLine(" value, bool? returnEmptyAsNull = false)");
        source.AppendLine("    {");
        source.AppendLine("        var description = GetDescription(value);");
        source.AppendLine("        return returnEmptyAsNull == true && description.Length == 0 ? null : description;");
        source.AppendLine("    }");
        source.Append("    internal static string? ToAttributeValue(this ").Append(typeName).AppendLine("? value, bool? returnEmptyAsNull = false)");
        source.AppendLine("        => value.HasValue ? ToAttributeValue(value.Value, returnEmptyAsNull) : null;");
        source.Append("    internal static string? ToAttributeValue(this ").Append(typeName).Append(" value, ").Append(typeName).AppendLine(" isNull, bool? returnEmptyAsNull = false)");
        source.AppendLine("        => value == isNull ? null : ToAttributeValue(value, returnEmptyAsNull);");
        source.Append("    internal static string? ToAttributeValue(this ").Append(typeName).Append("? value, ").Append(typeName).AppendLine(" isNull, bool? returnEmptyAsNull = false)");
        source.AppendLine("        => value.HasValue ? ToAttributeValue(value.Value, isNull, returnEmptyAsNull) : null;");
        source.Append("    internal static string GetDescription(this ").Append(typeName).AppendLine(" value)");
        source.AppendLine("        => value switch");
        source.AppendLine("        {");
        var fields = enumType.GetMembers().OfType<IFieldSymbol>().Where(field => field.HasConstantValue);
        foreach (var group in fields.GroupBy(field => field.ConstantValue))
        {
            // Limitation: aliases with different descriptions use the first declared member.
            // This can differ from runtime name selection, which is unspecified for duplicate values.
            var field = group.First();
            var constant = Convert.ToString(field.ConstantValue, CultureInfo.InvariantCulture);
            var suffix = field.ConstantValue is ulong ? "UL" : "L";
            source.Append("            (").Append(typeName).Append(")(").Append(constant).Append(suffix).Append(") => ");
            source.Append(SymbolDisplay.FormatLiteral(GetDescription(field), true)).AppendLine(",");
        }

        source.AppendLine("            _ => string.Empty,");
        source.AppendLine("        };");
    }

    private static string GetDescription(IFieldSymbol field)
    {
        var attribute = field.GetAttributes().FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == "System.ComponentModel.DescriptionAttribute");
        if (attribute is { ConstructorArguments.Length: 0 })
        {
            return string.Empty;
        }

        return attribute?.ConstructorArguments.FirstOrDefault().Value as string ?? field.Name.ToLowerInvariant();
    }
}