// ------------------------------------------------------------------------
// This file is licensed to you under the MIT License.
// ------------------------------------------------------------------------

using System.Text;
using FluentUI.Demo.DocApiGen.Abstractions;
using FluentUI.Demo.DocApiGen.Models.SummaryMode;

namespace FluentUI.Demo.DocApiGen.Formatters;

/// <summary>
/// Formats documentation output as C# code.
/// Only supports Summary mode data.
/// </summary>
public class CSharpOutputFormatter : IOutputFormatter
{
    /// <inheritdoc/>
    public string FormatName => "csharp";

    /// <inheritdoc/>
    public string Format(object data)
    {
        if (data == null)
        {
            throw new ArgumentNullException(nameof(data));
        }

        if (data is not SummaryDocumentationData summaryData)
        {
            throw new InvalidOperationException(
                $"CSharpOutputFormatter only supports SummaryDocumentationData. Received: {data.GetType().Name}");
        }

        return GenerateCSharpCode(summaryData);
    }

    private static string GenerateCSharpCode(SummaryDocumentationData data)
    {
        var sb = new StringBuilder();

        // License header
        sb.AppendLine("// ------------------------------------------------------------------------");
        sb.AppendLine("// This file is licensed to you under the MIT License.");
        sb.AppendLine("// ------------------------------------------------------------------------");
        sb.AppendLine();

        // Auto-generated comment
        sb.AppendLine("// <auto-generated>");
#pragma warning disable CA1305 // Specify IFormatProvider
        sb.AppendLine($"//     This code was generated by a tool on {data.Metadata.DateUtc}.");
        sb.AppendLine($"//     Assembly: {data.Metadata.AssemblyVersion}");
        sb.AppendLine($"//     Mode: {data.Metadata.Mode}");
#pragma warning restore CA1305 // Specify IFormatProvider
        sb.AppendLine("//");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Using statements
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine();

        // Namespace and class
        sb.AppendLine("namespace FluentUI.Demo.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides access to API documentation comments.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class CodeComments");
        sb.AppendLine("{");

        // Dictionary
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Dictionary containing all API documentation.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static readonly IDictionary<string, (string Summary, string Signature)> SummaryData = new Dictionary<string, (string Summary, string Signature)>");
        sb.AppendLine("    {");

        // Add entries
        foreach (var entry in data.Components)
        {
            var key = EscapeString(entry.Key);
            var summary = EscapeString(entry.Value.Summary);
            var signature = EscapeString(entry.Value.Signature);
            
#pragma warning disable CA1305 // Specify IFormatProvider
            sb.AppendLine($"        {{ \"{key}\", (\"{summary}\", \"{signature}\") }},");
#pragma warning restore CA1305 // Specify IFormatProvider
        }

        sb.AppendLine("    };");
        sb.AppendLine();

        // Helper methods
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the signature for a member.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string GetSignature(MemberInfo member)");
        sb.AppendLine("    {");
        sb.AppendLine("        var key = $\"{member.DeclaringType?.FullName}.{member.Name}\";");
        sb.AppendLine("        return SummaryData.TryGetValue(key, out var data) ? data.Signature : string.Empty;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the summary for a member.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string GetSummary(MemberInfo member)");
        sb.AppendLine("    {");
        sb.AppendLine("        var key = $\"{member.DeclaringType?.FullName}.{member.Name}\";");
        sb.AppendLine("        return SummaryData.TryGetValue(key, out var data) ? data.Summary : string.Empty;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return string.Empty;
        }

        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
