name: Deploy docs and demo preview site

on:
  # Allow manually running the workflow
  workflow_dispatch:

  push:
    branches:
      - dev
    paths-ignore:
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build_deploy_demo:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and deploy Demo site
    env:
      DOTNET_VERSION: "net9.0"
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      PROJECT: "examples/Demo/Client/FluentUI.Demo.Client.csproj"
      BUILD_ARCH: "Any CPU"
      BUILD_CONFIG: "Release"
      SKIP_DEPLOY_ON_MISSING_SECRETS: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: .NET Setup SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: .NET Setup SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          dotnet-quality: preview

      - name: .NET Builld
        run: dotnet build ${{ env.PROJECT }} -c ${{ env.BUILD_CONFIG }} -o publish -f ${{ env.DOTNET_VERSION }} -r linux-x64 --self-contained=true -p:BuildNumber=$BUILD_NUMBER -p:SourceRevisionId=$GITHUB_SHA -p:ContinuousIntegrationBuild=true

      - name: .NET Publish
        run: dotnet publish ${{ env.PROJECT }} -c ${{ env.BUILD_CONFIG }} -o publish -f ${{ env.DOTNET_VERSION }} -r linux-x64 --self-contained=true -p:BuildNumber=$BUILD_NUMBER -p:SourceRevisionId=$GITHUB_SHA -p:ContinuousIntegrationBuild=true

      - name: Deploy demo site to new Azure Static Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_PEBBLE_0DC79CB03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish/wwwroot"
          api_location: "Api"
          output_location: "publish/wwwroot"
          skip_api_build: true
          skip_app_build: true
          production_branch: 'dev'

  destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request on new Azure Static Web App
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_PEBBLE_0DC79CB03 }}
          action: "close"
