name: Build microsoft.fast.templates.fluentui

pr: none
trigger: none

pool:
  vmImage: 'windows-2022'

variables:
  project: 'templates/Microsoft.Fast.Templates.FluentUI.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet tools

- task: UseDotNet@2
  displayName: 'Install .NET 6.0'
  inputs:
    version: 6.0.408
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: 'Install .NET 7.0'
  inputs:
    version: 7.0.203
    includePreviewVersions: true

- task: UseDotNet@2
  displayName: 'Install .NET 8.0'
  inputs:
    version: 8.0.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Install dependencies
  inputs:
    command: 'restore'
    projects: $(project)

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: $(project)
    versioningScheme: 'off'

- task: EsrpCodeSigning@3
  displayName: Code Signing Assemblies (Authenticode Signing)
  inputs:
    ConnectedServiceName: 'FAST-NuGet-Publishing-SC'
    FolderPath: '$(Build.ArtifactStagingDirectory)'
    Pattern: | 
      **/*.nupkg
    UseMinimatch: true
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetSign",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        },
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '200'
    MaxRetryAttempts: '5'

- task: NuGetCommand@2
  displayName: Publish to NuGet
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)\*.nupkg;'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NugetServiceConnect'